### ISSUE TITLE
请求更换看漫画网址

### ISSUE THREAD

**Issue by saasddsaasdd** [feilongfl/Cimoc#10]
大佬，看漫画的源可以通过https://tw.manhuagui.com 直接访问，无需翻墙，跪求大佬添加。这是我最喜欢的一个源，看着它从seemh到ikanman到现在的manhuagui，他的图库和图源都是最棒的。

**Comment by feilongfl** [comment]
我不常看这个源,简单查了一下代码,程序里面使用的是移动版网站,你这个域名的ip和移动版被解析在同一个ip上,看来是域名被墙的问题.

[tw.manhuagui.com](tw.manhuagui.com)是电脑板网站,适配需要点时间

**Comment by saasddsaasdd** [comment]
谢谢大佬回复，我以为只需要替换下网址就可以了。。。。谢谢大佬关注，另外需要通过https才可以

**Comment by feilongfl** [comment]
昨天晚上尝试更换了一下,不知道是我这边网络问题还是程序修改错误,没有梯子的话返回`connection reset by peer`搭上梯子就正常了

不确定原因,因为我这边梯子在路由器上,外网是用手机流量测试的,我可能需要改造一下我这边网络环境再进行测试

**Comment by zhongfly** [comment]
自从使用测试版后，看漫画源的漫画再也打不开了，也搜不到来自看漫画源的啦…
有无梯子均是如此…还不如原来的，我反倒觉得原来的源没墙

**Comment by zhihaofans** [comment]
@zhongfly 你可以在浏览器搜索漫画然后打开漫画页面会跳转到Cimoc app

**Comment by zhongfly** [comment]
我说过了…书架里来自看漫画源的漫画都打不开了，我觉得还是原来的源好用。可以单独把tw的源独立出来，以避免影响。

ps：在另一个设备中，无梯状态下如作者所说，解析错误。有梯才能正常使用

**Comment by feilongfl** [comment]
好吧,我这两天再试试
