### ISSUE TITLE
依作者搜索关键词传递问题

### ISSUE THREAD

**Issue by LenKiMo** [feilongfl/Cimoc#100]
1.4.22

案例：
http://m.dmzj.com/info/13117.html

通过 app 内建的搜索作者功能搜索同作者漫画时，会陷入无限读取状态。
通过该作者其他作品（同动漫之家源）搜索时，情况相同。但如果通过其它漫画源发起搜索作者时，便能够正常获取结果。
手动搜索コンノトヒロ，能够获取正常结果。

依目前来看可能感觉是作者姓名关键字在传递至搜索时出了问题，但为何只有动漫之家源如此则上不明确。
尚未找到其它类似案例。

**Comment by LenKiMo** [comment]
追加案例：
http://m.dmzj.com/info/16278.html

这次是平假名，与先前一样，从动漫之家源发起搜索作者时会无限转圈无法得到结果。但是从其它源（如动漫屋）发起搜索作者，或是直接搜索假名时便可正常得到结果。

可能问题就在动漫之家源对全非中文字符的作者名的传递上存在问题。

**Comment by feilongfl** [comment]
没能复现

![photo_2019-04-17_10-06-31](https://user-images.githubusercontent.com/10269596/56255727-81f53f00-60f8-11e9-9cdb-c59691d36a52.jpg)

**Comment by LenKiMo** [comment]
恩……我这里好像也恢复了。

可能考虑是不是当时的网络环境问题。既然已经恢复正常了就先 issue 了。

抱歉没能多调查再来回报。
