### ISSUE TITLE
进入特定漫画闪退

### ISSUE THREAD

**Issue by LenKiMo** [feilongfl/Cimoc#102]
Meizu Pro 6 Plus
Android 7.0.0
1.4.22

重现步骤：
- 将搜索范围限定为 CC 图库
- 使用关键字 默示录 进行搜索
- 得出搜索结果后，尝试进入其它漫画，可以正常读取话数列表
- 点击进入『勇气默示录：飞舞的妖精』
- 页面切换，闪退

目前没有发现其它类似情况。

**Comment by feilongfl** [comment]
这个漫画为什么闪退啊，调试时候什么错的没报直接就没了 :sob: 
之后再看看吧
