### ISSUE TITLE
关于主页面漫画封面显示问题

### ISSUE THREAD

**Issue by TenderMoon** [feilongfl/Cimoc#105]
请问能不能做成显示封面的正常大小而不是现在被切割的样子，封面也是特别值得欣赏的部分。无法发图片，就像喵呜app显示的那样😊

**Comment by feilongfl** [comment]
封面...可以点开欣赏 :joy:
小框框,拉伸更不好看

**Comment by TenderMoon** [comment]
![4D75270011F9F262432D2C15283A2885](https://user-images.githubusercontent.com/49451035/56211173-e3ca9000-6089-11e9-871a-ab1ad37a0361.jpg)

就是这样子觉得挺不错的  或者有分栏/网格的选择

**Comment by feilongfl** [comment]
这样的话每页显示的漫画就少了，找漫画滑动距离会变长，懒人表示不想动。。。

之后可以考虑可选

**Comment by TenderMoon** [comment]
那张图是我用手机截的啦  我一般用平板看   平板上显示就会没有适应  变成图里这样显示不全，图2.3是参考~以后有空可以考虑下~
![9E59D7E7E4D505065E468CF3019EF2F2](https://user-images.githubusercontent.com/49451035/56408819-c7586e80-62a8-11e9-807f-41ae31c3a1a9.jpg)
![D2A5C31E3DD4F5020D0CAB956B7C0E17](https://user-images.githubusercontent.com/49451035/56408821-c8899b80-62a8-11e9-9c47-60ea375deb4e.jpg)
![739E989F6E2ADF2918A4BCC5F92F925B](https://user-images.githubusercontent.com/49451035/56408839-d8a17b00-62a8-11e9-8688-1b81e70ab3cd.jpg)
