### ISSUE TITLE
关于合并PR

### ISSUE THREAD

**Issue by RebornQ** [feilongfl/Cimoc#106]
@feilongfl  前几天看到你提交了个PR（地址：[https://github.com/RebornQ/Cimoc/pull/2](https://github.com/RebornQ/Cimoc/pull/2)），我觉得合并是个好主意😄，但是我只是想部分合并（有些功能是身边朋友需要才写的🙈）。我试过cherry pick，但会多出很多重复的commit（强迫症受不了🙈），想跟你了解一下你是怎么合并我那部分的代码的😄。在github上找不到你的联系方式，只能开个issue了😂，这是我邮箱ren.xiaoyao58@gmail.com

**Comment by feilongfl** [comment]
feilongphone@gmail.com
其实我是人肉merge的 :joy:

**Comment by feilongfl** [comment]
还有我除了更新没删什么功能，好像有个音量键翻页叫我删了，因为本来程序里面就有，自定义点击事件按下音量键

**Comment by RebornQ** [comment]
@feilongfl  那个音量键翻页是因为我有个好朋友叫我实现，我说本来就有啊，他看了一下，说原来隐藏的这么深，叫我把它提取出来明显一点，我就顺手搞了一下😆

**Comment by feilongfl** [comment]
@RebornQ 其实写在下面那行小字里面了:joy:
