### ISSUE TITLE
汗汗漫画转汗汗酷漫后大量漫画报错

### ISSUE THREAD

**Issue by LenKiMo** [feilongfl/Cimoc#109]
# 这是一个漫画源问题

## 出现错误的漫画源
汗汗酷漫

## 您搜索/观看的漫画名称或关键字以及访问链接

http://hhaass.com/comic/3296
http://hhaass.com/comic/21725
http://hhaass.com/comic/5239
http://hhaass.com/comic/23627

## 在以下环节中出现错误
- [ ] 搜索
- [x] 章节信息
- [x] 图片加载

所有报错漫画的所有页面均会加载为报错图片：图片没有找到。

## 你是否使用科学上网工具
- [x] 是
- [ ] 否

但是即使关闭了也依旧如此。

## 你是否能够访问漫画源网页并成功加载漫画图片
- [ ] 是
- [x] 否

访问速度极慢，开启困难。上述链接由 Cimoc 分享获得，但实际点击进入后，会跳转到 hhimm.com，而链接预览中显示的域名又是 hhcool.com。
关闭上网工具后，访问上述链接可能遭遇 Connection Reset。

## 您手机的系统版本
- [ ] 原生(AOSP/LL/RR/Mokee等)
- [x] 国产(小米/氢氧/锤子)
具体版本: 
Android 7.0.0

## 您使用的cimoc版本
V1.4.25

至少在我的设备与网络环境下，原有的汗汗漫画一直可以正常使用并不存在问题。

此次更新后，原汗汗漫画的源全部变成 (null) 且无法加载章节列表，解析失败。

希望能够恢复原汗汗漫画的源，它在收录一些罕见或被和谐漫画方面颇有用处。

**Comment by feilongfl** [comment]
我是看了 https://github.com/feilongfl/Cimoc/issues/96 说不能用我才改的 :cry: 
好吧，写之前没测试下原本的能用不 :sob: 我就看网页跳转了就给换了 :crying_cat_face:

**Comment by LenKiMo** [comment]
其实也可以考虑二者皆保留，毕竟原来的汗汗漫画长期都是稳定可用的。现在的可以作为调整后的备选。

**Comment by feilongfl** [comment]
问下汗汗漫畫和手机汗汗两个源都是可用的么？

**Comment by feilongfl** [comment]
我checkout了v1.4.22但是两个源都搜索不到漫画的

**Comment by ckn4** [comment]
之前的汗汗在使用工具的情况下是可以用的，手机汗汗不行。你修改过的汗汗酷漫会出现图片没有找到的问题。

**Comment by feilongfl** [comment]
> 之前的汗汗在使用工具的情况下是可以用的，手机汗汗不行。你修改过的汗汗酷漫会出现图片没有找到的问题。

感谢回复，请给出不能访问的名字

**Comment by LenKiMo** [comment]
> 问下汗汗漫畫和手机汗汗两个源都是可用的么？

在我这汗汗漫画一直可用，手机汗汗一直不可用（从未在搜索结果里出现过）。
由于手机长期挂载工具，没有观察不挂载工具下两个源的情况。

**Comment by feilongfl** [comment]
恢复了汗汗漫画

**Comment by LenKiMo** [comment]
已确认到汗汗漫画恢复且能够正常使用，关闭 issue。
