### ISSUE TITLE
更新后看漫画时闪退

### ISSUE THREAD

**Issue by Steve-337** [feilongfl/Cimoc#110]
更新到最新版后，点击已经下载的漫画时直接闪退（安卓4.1.2，三星）（仅限卷纸模式）

**Comment by feilongfl** [comment]
无辜的表示，我这两天没动下载部分啊 :scream: 

好吧，是所有的卷纸都崩溃o.o

**Comment by feilongfl** [comment]
应该不闪退了:smile:
