### ISSUE TITLE
希望能支持webdav备份

### ISSUE THREAD

**Issue by rhjdvsgsgks** [feilongfl/Cimoc#117]
可参考 [阅读](https://github.com/gedoor/MyBookshelf)

**Comment by feilongfl** [comment]
我觉得如果使用webdev的话应该有专门的网盘软件，设置同步目录就可以了，没什么内置的必要性呢

**Comment by rhjdvsgsgks** [comment]
nextcloud之类的自建网盘的客户端很难用，有很多问题（如不支持断点续传），还不如用网页版

**Comment by feilongfl** [comment]
webdav这边应该没这么惨吧,我是用的`syncthing`,之前弄过nextcloud,不过和我需求不太一样就没怎么弄了

**Comment by rhjdvsgsgks** [comment]
`syncthing`之前也用过，因为服务器在国外，小文件还好，大文件一碰到网络不稳就会停止同步，等它半天也不会自动恢复，只有手动把`syncthing`停止运行再打开才能继续同步。所以我现在干脆直接用`nextcloud`+支持webdav的客户端手动同步🤣

**Comment by feilongfl** [comment]
看来我们环境不太一样,我server在家里面,在几个设备同步一些照片电子书之类的
