### ISSUE TITLE
关于翻页模式的一个bug

### ISSUE THREAD

**Issue by rhjdvsgsgks** [feilongfl/Cimoc#118]
使用翻页模式，阅读方向设为从左到右，只有从前一章的第一页向前翻才能到达下一章，即在第一章的第一页从左往右划才能到达第二章

**Comment by feilongfl** [comment]
:flushed: 没发现这个问题

**Comment by rhjdvsgsgks** [comment]
从老版本升级上来没有这个bug，清除数据后打开软件不修改设置随便搜索一部漫画，跳转到第一章最后一页往后划即可复现
