### ISSUE TITLE
动漫之家源关键字搜索没有结果

### ISSUE THREAD

**Issue by pkszzcq** [feilongfl/Cimoc#119]
# 这是一个漫画源问题

> 请您在提交本问题前仔细完成下面问题以便更好地解决问题.
> 如果有多个漫画源出错，请不要合并在一起，谢谢

## 出现错误的漫画源
动漫之家
## 您搜索/观看的漫画名称或关键字以及访问链接
任意。例如电锯人
https://manhua.dmzj.com/dianjuren
## 在以下环节中出现错误
- [x] 搜索
- [ ] 章节信息
- [ ] 图片加载

## 你是否使用科学上网工具
- [ ] 是
- [x] 否

## 你是否能够访问漫画源网页并成功加载漫画图片
- [x] 是
- [ ] 否

## 您手机的系统版本
- [ ] 原生(AOSP/LL/RR/Mokee等)
- [x] 国产(小米/氢氧/锤子)
具体版本: miui10

## 您使用的cimoc版本
V1.4.32

不包含v2。用夜神模拟器试了一下也不行。点开图源，动漫之家，点击放大镜倒是有搜索结果。有历史的漫画也可以正常打开并观看。试了下Arachnid-27/comic版本动漫之家/v2源我都是正常的

**Comment by sunbeams001** [comment]
@feilongfl 我这边也重现了，看代码是 dmzj 源里这个搜索方法 `getSearchRequest` 内容被注释了，调试看来不挂代理下可以搜到东西
这里是有什么原因吗，希望能重新启用这个源

**Comment by LenKiMo** [comment]
目前发现了一个新的情况，动漫之家源可能可以接通一些被隐藏（下架？）的漫画。

案例：
明明从最强职业《龙骑士》转职成了初级职业《送货人》、却为何依然备受勇者们的青睐呢
http://m.dmzj.com/info/42919.html

这部漫画在我的设备上过去以【动漫之家】源收藏，还能正常连通观看。但是如果以相关关键词搜索，则无法获得【动漫之家V2】的结果，将上述链接分享给 Cimoc，也会被直接提示解析失败（猜测是调用了 V2 源进行解析）。
如果重新启用这个源，可能可以解决一些隐藏漫画在 V2 下失效的问题。

**Comment by zmw0510** [comment]
这个也无法被搜索到
https://manhua.dmzj.com/daidaoshiguwucunshi
无论是动漫之家还是动漫之家V2源,都不行.去图源里看更新列表,也找不到(刚更新的)
tachiyomi可以正常搜索到此漫画,应该有办法可以解决吧?

**Comment by pkszzcq** [comment]
> 这个也无法被搜索到
> https://manhua.dmzj.com/daidaoshiguwucunshi
> 无论是动漫之家还是动漫之家V2源,都不行.去图源里看更新列表,也找不到(刚更新的)
> tachiyomi可以正常搜索到此漫画,应该有办法可以解决吧?

其实这就是前面人说过的问题了。动漫之家有些漫画是被隐藏了的，包括动漫之家官方app也无法直接搜索。从原版cimoc的表现来看，动漫之家源是可以搜索到隐藏漫画的，但v2源是不可以的。因此我们才会希望能够修复无法被替代的动漫之家源

**Comment by feilongfl** [comment]
> 这个也无法被搜索到
> https://manhua.dmzj.com/daidaoshiguwucunshi
> 无论是动漫之家还是动漫之家V2源,都不行.去图源里看更新列表,也找不到(刚更新的)
> tachiyomi可以正常搜索到此漫画,应该有办法可以解决吧?

看了下这个，网页上写着国家政策什么的，翻了下tachiyomi的dmzj，他用的`http://s.acg.dmzj.com/comicsum/search.php`搜索结果

**Comment by pkszzcq** [comment]
更新了1.4.33后，发现dmzj源有些漫画搜索不到。现在发现的有
《虽然我也想脱宅》
https://manhua.dmzj.com/suiranwoyexiangtuozhai
《成为我的下仆吧》
https://manhua.dmzj.com/cwdxpb
《喜欢上了的话、就结束了》
https://manhua.dmzj.com/xihuanshangledehuajiujieshule
《7thGarden》
https://manhua.dmzj.com/7thgarden
《召唤！她是黄漫女主角》
https://manhua.dmzj.com/zhaohuantashihuangmannvzhujue

**Comment by feilongfl** [comment]
> 更新了1.4.33后，发现dmzj源有些漫画搜索不到。现在发现的有
> 《虽然我也想脱宅》
> https://manhua.dmzj.com/suiranwoyexiangtuozhai
> 《成为我的下仆吧》
> https://manhua.dmzj.com/cwdxpb
> 《喜欢上了的话、就结束了》
> https://manhua.dmzj.com/xihuanshangledehuajiujieshule
> 《7thGarden》
> https://manhua.dmzj.com/7thgarden
> 《召唤！她是黄漫女主角》
> https://manhua.dmzj.com/zhaohuantashihuangmannvzhujue

这些`动漫之家v2`源可以搜索到

**Comment by pkszzcq** [comment]
> 这些`动漫之家v2`源可以搜索到
但是从上面的共同点发现，似乎所有的完结漫画该源都没法搜索到。上述的除了7thgarden以外都是完结漫画，试了搜索其他的完结漫画也是可以复现
