### ISSUE TITLE
当搜索内容是日文的时候会搜索不出结果

### ISSUE THREAD

**Issue by mixjam** [feilongfl/Cimoc#12]
有时候想搜索一些作者的相关作品，但是输入日文名一直出不来搜索结果，好像原先的那个可以输入日文搜索？

**Comment by feilongfl** [comment]
默默问下支持的那几个网站用日文能搜出来吗,如果能的话请给个链接.

@waxleid

**Comment by mixjam** [comment]
之前那个好像支持搜作者名字的，记不清了。而且好像现在这个也不能搜索英文名（例如：new game；源网（动漫之家、看漫画、57漫画等）可以搜到）@feilongfl /又试了下，可以通过英文搜，但是大小写要与漫画名一致，源网不需要（源网输入new game ；软件输入New Game）。/原先的应用可以搜作者的日文名来找漫画，现在这个搜不了应该（不知道是不是原软件没更新源网的原因，只有动漫之家和57漫画的源可以）

**Comment by feilongfl** [comment]
1. 过滤漫画时候出现了大小的问题
1. 请提供几个日文漫画家名字，我只会行く行くやめで什么的:sweat_smile:

**Comment by mixjam** [comment]
凉川りん，春场ねぎ，ミウラタダヒロ @feilongfl

**Comment by waxleid** [comment]
@feilongfl

**Comment by feilongfl** [comment]
@waxleid 今天调整了搜索策略,应该修复了这个问题
