### ISSUE TITLE
能否在主页上添加进度信息

### ISSUE THREAD

**Issue by song-zi** [feilongfl/Cimoc#125]
有些漫画会隔三差五更新，收藏的多了一个一个进去找更新章节不太现实。

**Comment by feilongfl** [comment]
直接点继续阅读不可以么 :confused:

**Comment by song-zi** [comment]
我的意思是我在书架上看不到漫画是否更新，因为书架上漫画比较多，一个个看不现实。


 
---原始邮件---
发件人: "fei long"<notifications@github.com>
发送时间: 2019年5月1日(星期三) 上午8:18
收件人: "feilongfl/Cimoc"<Cimoc@noreply.github.com>;
抄送: "lisw26"<1027749717@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [feilongfl/Cimoc] 能否在主页上添加进度信息 (#125)



直接点继续阅读不可以么 😕

**Comment by feilongfl** [comment]
检查更新之后右上角有一个色块的

**Comment by song-zi** [comment]
这功能竟然要主动开启，以前一直不知道有这功能。


 
---原始邮件---
发件人: "fei long"<notifications@github.com>
发送时间: 2019年5月1日(星期三) 上午9:13
收件人: "feilongfl/Cimoc"<Cimoc@noreply.github.com>;
抄送: "lisw26"<1027749717@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [feilongfl/Cimoc] 能否在主页上添加进度信息 (#125)



检查更新之后右上角有一个色块的

**Comment by feilongfl** [comment]
> 这功能竟然要主动开启，以前一直不知道有这功能。
> […](#)
> ---原始邮件--- 发件人: "fei long"<notifications@github.com> 发送时间: 2019年5月1日(星期三) 上午9:13 收件人: "feilongfl/Cimoc"<Cimoc@noreply.github.com>; 抄送: "lisw26"<1027749717@qq.com>;"Author"<author@noreply.github.com>; 主题: Re: [feilongfl/Cimoc] 能否在主页上添加进度信息 (#125) 检查更新之后右上角有一个色块的 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.

这功能一直都有的,只是自动检查需要手动开启
