### ISSUE TITLE
能否在书架上做个简单的检索？

### ISSUE THREAD

**Issue by searock2012** [feilongfl/Cimoc#128]
和大妈之家那种按首字母分类就行，大几百本找起来太累了（貌似其他官方app也没有搞这个的，考虑到大家收藏漫画都不多吗）
特别是本地阅读更需要检索，其实本地阅读还是挺重要的，很多漫画都是汉化组早早弃坑，在线就开头几话，后面全得自己下生肉，能支持压缩包阅读就更完美了

**Comment by ClearSights** [comment]
支持对已收藏漫画分类，漫画收藏多了有时候不太好找

**Comment by zhongfly** [comment]
我也一直希望完善对收藏漫画的管理，比如可以按漫画源分类，或者提示检查更新失败的漫画(多半是下架之类的)，或者是搜索已收藏的漫画
