### ISSUE TITLE
可不可以重新添加"图源"页面？

### ISSUE THREAD

**Issue by GodSavior** [feilongfl/Cimoc#13]
Arachnid版的侧栏里可以进入图源页面，点进插件后可以选择根据漫画更新时间来搜索，看看最近有没有什么新漫画。换过来这边之后功能被阉割了有点不适应...一想到有新漫画可是自己却不知道就浑身不自在(平常不关注贴吧/各种论坛)
至于我为什么不使用A版是因为看漫画插件几个月前开始无法直接从图源页按条件搜索最近更新的漫画了，只能先透过其他插件比如大妈之家先找到新漫画然后再透过全局搜索才能进入看漫画的详情页面。
*A版看漫画插件搜索漫画/检查更新都没有问题可以直接进入就只有图源页里的按条件搜索出错...

**Comment by feilongfl** [comment]
原来图源界面能搜索:cold_sweat:好吧，我以为那个界面只是开关就给删了:sweat:

另外，按照你的需求，我觉得订阅漫画更新的rss更合适，你可以在feedly或者其他平台找到合适的rss

**Comment by feilongfl** [comment]
顺便软件是支持网页调用的，你可以登录支持的那几个漫画站，选好漫画使用软件打开

**Comment by kirito990701** [comment]
好吧感谢大佬

**Comment by RTM945** [comment]
😰把那个开关加回去吧

**Comment by feilongfl** [comment]
fixed at https://github.com/feilongfl/Cimoc/releases/tag/v1.4.8.8053

**Comment by GodSavior** [comment]
666感谢大佬
