### ISSUE TITLE
应用被腾讯提示恶意软件

### ISSUE THREAD

**Issue by zhihaofans** [feilongfl/Cimoc#132]
手机:三星note9 (Android 9)
安全检测是腾讯提供的功能，所以只能看到是恶意软件，但不知道原因

![Screenshot_20190517-224709_Smart Manager.jpg](https://i.loli.net/2019/05/17/5cdec97ded88753851.jpg)

**Comment by feilongfl** [comment]
难道是因为腾讯动漫？？

**Comment by zhihaofans** [comment]
> 难道是因为腾讯动漫？？

之前pornhub客户端就会提示色情软件，这次就没有任何提示，我觉得有可能是因为腾讯动漫

**Comment by feilongfl** [comment]
> > 难道是因为腾讯动漫？？
> 
> 之前pornhub客户端就会提示色情软件，这次就没有任何提示，我觉得有可能是因为腾讯动漫

反正代码都开源了，编译是travis编译的，不放心的自己编译就好了 :smile:

**Comment by zhihaofans** [comment]
> > > 难道是因为腾讯动漫？？
> > 
> > 
> > 之前pornhub客户端就会提示色情软件，这次就没有任何提示，我觉得有可能是因为腾讯动漫
> 
> 反正代码都开源了，编译是travis编译的，不放心的自己编译就好了 😄

我去腾讯官网( https://m.qq.com/security_lab/scans_online.jsp )查了一下，是"a.gray.sexcartoon"，看名字估计是色情软件，最好在README提示会被腾讯报毒

**Comment by WSQAQ** [comment]
华为安全中心也是报毒。。。

**Comment by xxxloli123** [comment]
自己编译 不了啊
Failed to notify build listener.

**Comment by feilongfl** [comment]
> 自己编译 不了啊
> Failed to notify build listener.

自动集成没有报错，请检查你的开发环境。
