### ISSUE TITLE
反馈+建议

### ISSUE THREAD

**Issue by Kyolor** [feilongfl/Cimoc#133]
@feilongfl   修正：2019/5/25

手机系统：【Android 8.1公测版】一加5T H2OS 第19版 (181025)
Cimoc版本：v1.4.33（412）

以下仅为个人意见，希望Cimoc越做越好，开发者辛苦了！

----------------------------------------------------------------------
一、图源
1、建议修复
⑴ 汗汗酷漫 http://www.hhimm.com/
搜索基本无，或者图片全失效，图源无问题

⑵ 漫画台：网站更新，解析源出问题

2、建议删除
⑴ 无效源
漫画Love、MangaNel、吹雪漫画（结果可搜，就是看不了哈哈）
CC图库（跳转动漫屋，让你怎么看 ，喝茶）

⑵ 收费源（解析不了，不如直接下APP）
腾讯动漫、网易漫画、有妖气、动漫屋 、咪咕漫画、布卡漫画

⑶ 余下源
Ehentai：开着小飞机，也搜不出啥，是我搜索姿势有误？？？不友好

CC漫画  http://www.ccdm9.com/  搜索服务器错误，APP搜不出结果
以下有效，但该图源资源老、少，缺失章节
WEB：http://www.ccmh7.com/ 
WAP：http://m.ccdm9.com/      http://m.ccmh7.com/

动漫之家 、动漫狂：热门资源大多没了
汗汗漫画：资源主要是日漫，但资源更新慢，排序不佳，除此之外，还要开小飞机 

------------------------------------------------------------------------------------------
二、功能增设
1、图源
希望增加搜索图源、图源备注、全选、反选、校验、置顶功能
图源备注：说明下要fan、要繁体搜（如Webtoon），搜索间隔   

2、收藏
收藏建议弄成多层书架，增加搜索书架漫画、管理漫画功能（真的很有必要呀！！！）
本地那栏没必要，可以直接增加一个本地导入书架功能。 

3、阅读
在阅读漫画过程，可以阅读设置（这样就方便许多了），这点异次元做的真不错
CImoc在这方面主要依靠的是自定义点击/长按，以及设置

4、换源
将搜索到的结果标题一致的聚合，可切换源  （很棒）
在这点上，异次元主要还有一个问题：换源不是进入到漫画阅读，而是漫画详情

----------------------------------------------------------------------------------------
三、个人倾向
希望之后也不要添加SEX源（见仁见智），Cimoc图源做好少而精就好

**Comment by Kyolor** [comment]
最终Cimoc图源保留
------------------------------------
正版：
Webtoon (韩漫) 、漫画台 (国漫，解析修复)

免费：
看漫画、57漫画 (加载慢)、土豪漫画、漫画DB、我要去漫画、扑飞漫画、漫画堆、汗汗酷漫（修复）
99770漫画、2animx、古风漫画、百年漫画

**Comment by Kyolor** [comment]
汗汗酷漫马甲
--------------------------------------------------
⑴ WEB端 
一拳漫画http://www.1manhua.net/   
虎虎漫画http://www.huhudm.com/ （部分漫画不提供试看）

⑵ WAP端 （统统juju）
DDMMCC http://ddmmcc.com/   BBSSOO  http://bbssoo.com/  SSOONN http://ssoonn.com/

**Comment by feilongfl** [comment]
感谢整理，一般不会删除图源，之前加的漫画源有点多了，感觉有点维护不过来了:joy:不过常用的应该都正常

**Comment by aawwsslll** [comment]
只同意删除无效源。
