### ISSUE TITLE
博阅T80D搜索bug

### ISSUE THREAD

**Issue by mojinpan** [feilongfl/Cimoc#134]
使用博阅T80D进行漫画搜索后,在列出的漫画清单上点击后,无法进入其页面,而是返回到搜索输入关键字的页面.

硬件:博阅 likebook T80D
内核:安卓6.0
系统版本: BYread-V1.0.7-2019031914

log:
MODEL: Likebook-T80D
SDK: 23

RELEASE: 6.0.1

Unable to start activity ComponentInfo{com.hiroshi.cimoc/com.hiroshi.cimoc.ui.activity.DetailActivity}: android.database.sqlite.SQLiteException: no such column: T.URL (code 1): , while compiling: SELECT T."_id",T."SOURCE",T."CID",T."TITLE",T."COVER",T."HIGHLIGHT",T."LOCAL",T."UPDATE",T."FINISH",T."FAVORITE",T."HISTORY",T."DOWNLOAD",T."LAST",T."PAGE",T."CHAPTER",T."URL" FROM "COMIC" T  WHERE T."SOURCE"=? AND T."CID"=?

android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2427)
android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2487)
android.app.ActivityThread.-wrap11(ActivityThread.java)
android.app.ActivityThread$H.handleMessage(ActivityThread.java:1352)
android.os.Handler.dispatchMessage(Handler.java:102)
android.os.Looper.loop(Looper.java:148)
android.app.ActivityThread.main(ActivityThread.java:5431)
java.lang.reflect.Method.invoke(Native Method)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:772)
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:662)

**Comment by mojinpan** [comment]
log:
MODEL: Likebook-T80D
SDK: 23
RELEASE: 6.0.1

Unable to start activity ComponentInfo{com.hiroshi.cimoc/com.hiroshi.cimoc.ui.activity.DetailActivity}: android.database.sqlite.SQLiteException: no such column: T.URL (code 1): , while compiling: SELECT T."_id",T."SOURCE",T."CID",T."TITLE",T."COVER",T."HIGHLIGHT",T."LOCAL",T."UPDATE",T."FINISH",T."FAVORITE",T."HISTORY",T."DOWNLOAD",T."LAST",T."PAGE",T."CHAPTER",T."URL" FROM "COMIC" T  WHERE T."SOURCE"=? AND T."CID"=?

android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2427)
android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2487)
android.app.ActivityThread.-wrap11(ActivityThread.java)
android.app.ActivityThread$H.handleMessage(ActivityThread.java:1352)
android.os.Handler.dispatchMessage(Handler.java:102)
android.os.Looper.loop(Looper.java:148)
android.app.ActivityThread.main(ActivityThread.java:5431)
java.lang.reflect.Method.invoke(Native Method)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:772)
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:662)

**Comment by dongdong116** [comment]
博阅T103D同样出现问题

**Comment by feilongfl** [comment]
这个。。。
估计是博阅的系统改了什么吧，我用的boox，没有博阅可以测试

**Comment by succlz123** [comment]
博阅系统内即使全新安装也会自带一个版本号9的数据库，具体为什么会这样就不清楚了。

**Comment by feilongfl** [comment]
因为没有设备,我不知道这个是否被修复

**Comment by tmrsm** [comment]
T80D，更新到v1.4.39沒有這個問題了，謝謝大佬。

**Comment by yumanowang** [comment]
t65s有闪退问题

**Comment by feilongfl** [comment]
@succlz123 有设备能看下 @yumanowang 的问题么
