### ISSUE TITLE
[CS]漫画堆解析错误

### ISSUE THREAD

**Issue by Eanyuan** [feilongfl/Cimoc#137]
# 这是一个漫画源问题

> 请您在提交本问题前仔细完成下面问题以便更好地解决问题.
> 如果有多个漫画源出错，请不要合并在一起，谢谢

## 出现错误的漫画源
漫画堆
## 您搜索/观看的漫画名称或关键字以及访问链接
勇者死了
https://m.manhuadui.com/manhua/yongzhesile/
## 在以下环节中出现错误
- [ ] 搜索
- [ ] 章节信息
- [* ] 图片加载

## 你是否使用科学上网工具
- [ ] 是
- [* ] 否

## 你是否能够访问漫画源网页并成功加载漫画图片
- [* ] 是
- [ ] 否

## 您手机的系统版本
- [ ] 原生(AOSP/LL/RR/Mokee等)
- [* ] 国产(小米/氢氧/锤子)
具体版本: 
EMUI 9.0
## 您使用的cimoc版本
V1.4.33

**Comment by Steve-cn** [comment]
这个问题和我那个好像是一样的，都是无法加载图片，看来不是我手机问题了

**Comment by Steve-337** [comment]
我试了一下，可以正常加载图片，会不会是你的网络问题？（如DNS问题）

**Comment by feilongfl** [comment]
同没发现问题

**Comment by Eanyuan** [comment]
重新搜索了勇死，发现没问题，收藏后发现与原来收藏的勇死不为同一本，大概是网站重做了一次勇死网页，所以原来收藏的加载不出来
