### ISSUE TITLE
长时间翻阅同一漫画闪退

### ISSUE THREAD

**Issue by zhongfly** [feilongfl/Cimoc#14]
由于长时间一直阅读同一漫画常发生闪退现象，我猜测可能是由于缓存了过多图片导致。
重现方法如下：
以动漫之家v2源的“黑岩射手 天真之灵”为测试漫画，卷纸模式，阅读方向：从上到下
从最开始处开始阅读，以较快速度翻页以保证图片均已加载，翻页至第3卷(累计250页左右)，必然发生闪退

也许和设备内存小有关系吧?
话说没有log?

**Comment by zhongfly** [comment]
已证实与设备内存有关，另一有大内存的手机未出现该问题…
建议：缓存图片到一定大小自动清理…

**Comment by feilongfl** [comment]
我在性能工具上没有发现内存问题，资源都被正常回收了，请给出手机型号

**Comment by feilongfl** [comment]
小米2A无法复现 /(ㄒoㄒ)/~~

手里没有更低配置的手机了...

小米2A青春版 1+16g android6.0

**Comment by zhongfly** [comment]
Kindle fire hdx 7平板
运行内存1709
不知道我抓的log有没有用
剩余内存700M左右，快速翻动，加载图片100张左右，出现闪退



03-03 11:46:02.963   989  2048 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.hiroshi.cimoc/.ui.activity.MainActivity bnds=[0,1295][200,1600] (has extras)} from uid 10028 on display 0
03-03 11:48:08.894   989  1399 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.hiroshi.cimoc/.ui.activity.MainActivity bnds=[0,1295][200,1600] (has extras)} from uid 10028 on display 0
03-03 11:48:10.696   989  1399 I ActivityManager: START u0 {cmp=com.hiroshi.cimoc/.ui.activity.StreamReaderActivity (has extras)} from uid 10117 on display 0
03-03 11:48:26.738   989  1950 I WindowManager: WIN DEATH: Window{a05de54 u0 com.hiroshi.cimoc/com.hiroshi.cimoc.ui.activity.DetailActivity}
03-03 11:48:26.739   989  1967 I ActivityManager: Process com.hiroshi.cimoc (pid 18473) has died
03-03 11:48:26.743   989  1008 I WindowManager: WIN DEATH: Window{fb41337 u0 com.hiroshi.cimoc/com.hiroshi.cimoc.ui.activity.StreamReaderActivity}
03-03 11:48:26.746   989  1948 I WindowManager: WIN DEATH: Window{a40a032 u0 com.hiroshi.cimoc/com.hiroshi.cimoc.ui.activity.MainActivity}
03-03 11:48:26.915   989   989 W NotificationService: Object died trying to hide notification android.app.ITransientNotification$Stub$Proxy@577e671 in package com.hiroshi.cimoc
03-03 11:48:26.937   989   989 W NotificationService: Object died trying to show notification android.app.ITransientNotification$Stub$Proxy@8a9bc56 in package com.hiroshi.cimoc
03-03 11:48:26.937   989   989 W NotificationService: Object died trying to show notification android.app.ITransientNotification$Stub$Proxy@82b94d7 in package com.hiroshi.cimoc
03-03 11:52:34.955   989  2048 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10300000 cmp=com.hiroshi.cimoc/.ui.activity.MainActivity (has extras)} from uid 10028 on display 0
03-03 11:52:35.030   989  1948 I ActivityManager: Start proc 5559:com.hiroshi.cimoc/u0a117 for activity com.hiroshi.cimoc/.ui.activity.MainActivity
03-03 11:52:38.387   989  1009 I ActivityManager: START u0 {cmp=com.hiroshi.cimoc/.ui.activity.DetailActivity (has extras)} from uid 10117 on display 0
03-03 11:52:39.959   989 16108 I ActivityManager: START u0 {cmp=com.hiroshi.cimoc/.ui.activity.StreamReaderActivity (has extras)} from uid 10117 on display 0
03-03 11:54:29.191   989  1950 I ActivityManager: Process com.hiroshi.cimoc (pid 5559) has died
03-03 11:54:29.193   989  1967 I WindowManager: WIN DEATH: Window{96b0554 u0 com.hiroshi.cimoc/com.hiroshi.cimoc.ui.activity.StreamReaderActivity}
03-03 11:54:30.481   989   989 W NotificationService: Object died trying to hide notification android.app.ITransientNotification$Stub$Proxy@c4c9522 in package com.hiroshi.cimoc
03-03 11:54:30.481   989   989 W NotificationService: Object died trying to show notification android.app.ITransientNotification$Stub$Proxy@c580bb3 in package com.hiroshi.cimoc
03-03 11:55:46.598   989  2049 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10300000 cmp=com.hiroshi.cimoc/.ui.activity.MainActivity (has extras)} from uid 10117 on display 0
03-03 11:55:46.677   989  2046 I ActivityManager: Start proc 8240:com.hiroshi.cimoc/u0a117 for activity com.hiroshi.cimoc/.ui.activity.MainActivity
03-03 11:55:49.878   989  1948 I ActivityManager: START u0 {cmp=com.hiroshi.cimoc/.ui.activity.DetailActivity (has extras)} from uid 10117 on display 0
03-03 11:55:51.527   989  2044 I ActivityManager: START u0 {cmp=com.hiroshi.cimoc/.ui.activity.StreamReaderActivity (has extras)} from uid 10117 on display 0
03-03 11:56:08.721   989  2049 I ActivityManager: Process com.hiroshi.cimoc (pid 8240) has died
03-03 11:56:08.721   989  2049 W ActivityManager: Force removing ActivityRecord{5bd5d3a u0 com.hiroshi.cimoc/.ui.activity.StreamReaderActivity t5928}: app died, no saved state
03-03 11:56:08.724   989  1967 I WindowManager: WIN DEATH: Window{aad33e2 u0 com.hiroshi.cimoc/com.hiroshi.cimoc.ui.activity.DetailActivity}
03-03 11:56:08.728   989  1966 I WindowManager: WIN DEATH: Window{e5b677e u0 com.hiroshi.cimoc/com.hiroshi.cimoc.ui.activity.MainActivity}
03-03 11:56:08.733   989  2048 I WindowManager: WIN DEATH: Window{b9c031d u0 com.hiroshi.cimoc/com.hiroshi.cimoc.ui.activity.StreamReaderActivity}
03-03 11:56:09.645   989   989 W NotificationService: Object died trying to hide notification android.app.ITransientNotification$Stub$Proxy@7929fa1 in package com.hiroshi.cimoc
03-03 11:56:09.646   989   989 W NotificationService: Object died trying to show notification android.app.ITransientNotification$Stub$Proxy@d9735c6 in package com.hiroshi.cimoc
03-03 12:09:24.177   989  1399 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10300000 cmp=com.hiroshi.cimoc/.ui.activity.MainActivity (has extras)} from uid 10117 on display 0
03-03 12:09:24.219 20679 20679 I chatty  : uid=10117(com.hiroshi.cimoc) expire 356 lines
03-03 12:09:24.252   989  1966 I ActivityManager: Start proc 20679:com.hiroshi.cimoc/u0a117 for activity com.hiroshi.cimoc/.ui.activity.MainActivity
03-03 12:09:24.872 20679 20715 I chatty  : uid=10117(com.hiroshi.cimoc) expire 1 line
03-03 12:09:25.023 20679 20718 I chatty  : uid=10117(com.hiroshi.cimoc) expire 165 lines
03-03 12:09:25.075 20679 20723 I chatty  : uid=10117(com.hiroshi.cimoc) expire 7 lines
03-03 12:09:25.196   989  1019 I ActivityManager: Displayed com.hiroshi.cimoc/.ui.activity.MainActivity: +989ms
03-03 12:09:25.225 20679 20684 I chatty  : uid=10117(com.hiroshi.cimoc) expire 7 lines
03-03 12:09:26.857   989  2044 I ActivityManager: START u0 {cmp=com.hiroshi.cimoc/.ui.activity.DetailActivity (has extras)} from uid 10117 on display 0
03-03 12:09:26.886 20679 20679 I chatty  : uid=10117(com.hiroshi.cimoc) expire 173 lines
03-03 12:09:27.010 20679 20718 I chatty  : uid=10117(com.hiroshi.cimoc) expire 9 lines
03-03 12:09:27.068   989  1019 I ActivityManager: Displayed com.hiroshi.cimoc/.ui.activity.DetailActivity: +193ms
03-03 12:09:28.032   989 16108 I ActivityManager: START u0 {cmp=com.hiroshi.cimoc/.ui.activity.StreamReaderActivity (has extras)} from uid 10117 on display 0
03-03 12:09:28.462   989  1019 I ActivityManager: Displayed com.hiroshi.cimoc/.ui.activity.StreamReaderActivity: +405ms
03-03 12:09:29.446 20679 20689 I chatty  : uid=10117(com.hiroshi.cimoc) expire 1 line
03-03 12:09:32.950 20679 20687 I chatty  : uid=10117(com.hiroshi.cimoc) expire 40 lines
03-03 12:09:35.960 20679 20679 I chatty  : uid=10117(com.hiroshi.cimoc) expire 49 lines
03-03 12:09:36.053 20679 20718 I chatty  : uid=10117(com.hiroshi.cimoc) expire 2 lines
03-03 12:09:36.943 20679 20689 I chatty  : uid=10117(com.hiroshi.cimoc) expire 1 line
03-03 12:09:41.335   989 16108 I WindowManager: WIN DEATH: Window{ae637a6 u0 com.hiroshi.cimoc/com.hiroshi.cimoc.ui.activity.StreamReaderActivity}
03-03 12:09:41.335   989  1948 I ActivityManager: Process com.hiroshi.cimoc (pid 20679) has died
03-03 12:09:41.948   989   989 W NotificationService: Object died trying to hide notification android.app.ITransientNotification$Stub$Proxy@f9f2690 in package com.hiroshi.cimoc
03-03 12:09:41.949   989   989 W NotificationService: Object died trying to show notification android.app.ITransientNotification$Stub$Proxy@7e37b89 in package com.hiroshi.cimoc
03-03 12:09:41.951   989   989 W NotificationService: Object died trying to show notification android.app.ITransientNotification$Stub$Proxy@75878e in package com.hiroshi.cimoc
03-03 12:09:41.952   989   989 W NotificationService: Object died trying to show notification android.app.ITransientNotification$Stub$Proxy@72c2baf in package com.hiroshi.cimoc
03-03 12:10:54.359   989  2048 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10300000 cmp=com.hiroshi.cimoc/.ui.activity.MainActivity (has extras)} from uid 10117 on display 0
03-03 12:10:54.461   989  2049 I ActivityManager: Start proc 22040:com.hiroshi.cimoc/u0a117 for activity com.hiroshi.cimoc/.ui.activity.MainActivity
03-03 12:10:54.697 22040 22040 D SoLoader: adding application source: com.facebook.soloader.c[root = /data/app/com.hiroshi.cimoc-2/lib/arm flags = 0]
03-03 12:10:54.698 22040 22040 D SoLoader: adding backup  source: com.facebook.soloader.a[root = /data/data/com.hiroshi.cimoc/lib-main flags = 1]
03-03 12:10:54.698 22040 22040 D SoLoader: Preparing SO source: com.facebook.soloader.c[root = /data/app/com.hiroshi.cimoc-2/lib/arm flags = 0]
03-03 12:10:54.698 22040 22040 D SoLoader: Preparing SO source: com.facebook.soloader.a[root = /data/data/com.hiroshi.cimoc/lib-main flags = 1]
03-03 12:10:54.699 22040 22040 V fb-UnpackingSoSource: locked dso store /data/user/0/com.hiroshi.cimoc/lib-main
03-03 12:10:54.705 22040 22040 W System.err: 	at com.hiroshi.cimoc.App.onCreate(App.java:82)
03-03 12:10:54.707 22040 22040 W System.err: 	at com.hiroshi.cimoc.App.onCreate(App.java:82)
03-03 12:10:54.709 22040 22040 W System.err: 	at com.hiroshi.cimoc.App.onCreate(App.java:82)
03-03 12:10:54.711 22040 22040 W System.err: 	at com.hiroshi.cimoc.App.onCreate(App.java:82)
03-03 12:10:54.717 22040 22040 I fb-UnpackingSoSource: dso store is up-to-date: /data/user/0/com.hiroshi.cimoc/lib-main
03-03 12:10:54.717 22040 22040 V fb-UnpackingSoSource: releasing dso store lock for /data/user/0/com.hiroshi.cimoc/lib-main
03-03 12:10:54.849 22040 22040 W System.err: 	at com.hiroshi.cimoc.ui.activity.MainActivity.t(MainActivity.java:1506)
03-03 12:10:54.849 22040 22040 W System.err: 	at com.hiroshi.cimoc.ui.activity.BaseActivity.onCreate(BaseActivity.java:51)
03-03 12:10:54.852 22040 22040 W System.err: 	at com.hiroshi.cimoc.ui.activity.MainActivity.t(MainActivity.java:1506)
03-03 12:10:54.852 22040 22040 W System.err: 	at com.hiroshi.cimoc.ui.activity.BaseActivity.onCreate(BaseActivity.java:51)
03-03 12:10:55.087 22040 22083 D SoLoader: libimagepipeline.so not found on /data/data/com.hiroshi.cimoc/lib-main
03-03 12:10:55.087 22040 22083 D SoLoader: libimagepipeline.so found on /data/app/com.hiroshi.cimoc-2/lib/arm
03-03 12:10:55.095 22040 22083 E linker  : warning: unable to get realpath for the library "/data/app/com.hiroshi.cimoc-2/lib/arm/libimagepipeline.so". Will use given path.
03-03 12:10:55.184   989  1019 I ActivityManager: Displayed com.hiroshi.cimoc/.ui.activity.MainActivity: +792ms
03-03 12:10:56.858   989  1950 I ActivityManager: START u0 {cmp=com.hiroshi.cimoc/.ui.activity.DetailActivity (has extras)} from uid 10117 on display 0
03-03 12:10:57.082   989  1019 I ActivityManager: Displayed com.hiroshi.cimoc/.ui.activity.DetailActivity: +209ms
03-03 12:10:58.046   989  1009 I ActivityManager: START u0 {cmp=com.hiroshi.cimoc/.ui.activity.StreamReaderActivity (has extras)} from uid 10117 on display 0
03-03 12:10:58.236   989  1019 I ActivityManager: Displayed com.hiroshi.cimoc/.ui.activity.StreamReaderActivity: +173ms
03-03 12:11:59.171   989  1211 I ActivityManager: Process com.hiroshi.cimoc (pid 22040) has died
03-03 12:11:59.183   989  1948 I WindowManager: WIN DEATH: Window{f598566 u0 com.hiroshi.cimoc/com.hiroshi.cimoc.ui.activity.StreamReaderActivity}
03-03 12:11:59.186   989  2046 I WindowManager: WIN DEATH: Window{a28901d u0 com.hiroshi.cimoc/com.hiroshi.cimoc.ui.activity.MainActivity}
03-03 12:11:59.191   989  1104 W InputDispatcher: channel '43cca51 com.hiroshi.cimoc/com.hiroshi.cimoc.ui.activity.DetailActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
03-03 12:11:59.192   989  1104 E InputDispatcher: channel '43cca51 com.hiroshi.cimoc/com.hiroshi.cimoc.ui.activity.DetailActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
03-03 12:11:59.202   989  1008 I WindowManager: WIN DEATH: Window{43cca51 u0 com.hiroshi.cimoc/com.hiroshi.cimoc.ui.activity.DetailActivity}
03-03 12:11:59.202   989  1008 W InputDispatcher: Attempted to unregister already unregistered input channel '43cca51 com.hiroshi.cimoc/com.hiroshi.cimoc.ui.activity.DetailActivity (server)'
03-03 12:11:59.605   989   989 W NotificationService: Object died trying to hide notification android.app.ITransientNotification$Stub

**Comment by feilongfl** [comment]
转到 

https://github.com/feilongfl/Cimoc/issues/62
