### ISSUE TITLE
建议增加鼠绘漫画源

### ISSUE THREAD

**Issue by murongmingrui** [feilongfl/Cimoc#143]
建议增加鼠绘漫画源，毕竟看海贼王和猎人的小伙伴们还是蛮多的

**Comment by feilongfl** [comment]
参考 https://github.com/feilongfl/Cimoc/issues/68
顺便至少给个网址吧 :sweat_smile:

**Comment by murongmingrui** [comment]
https://www.ishuhui.com/

**Comment by feilongfl** [comment]
not stale
