### ISSUE TITLE
[CS]漫画堆

### ISSUE THREAD

**Issue by Kinn2021** [feilongfl/Cimoc#148]
# 这是一个漫画源问题

> 请您在提交本问题前仔细完成下面问题以便更好地解决问题.
> 如果有多个漫画源出错，请不要合并在一起，谢谢

## 出现错误的漫画源
漫画堆
## 在以下环节中出现错误
- [ ] 搜索
- [ ] 章节信息
- [ √] 图片加载

## 你是否使用科学上网工具
- [ ] 是
- [ √] 否

## 你是否能够访问漫画源网页并成功加载漫画图片
- [ √] 是
- [ ] 否

## 您手机的系统版本
- [ ] 原生(AOSP/LL/RR/Mokee等)
- [ √] 国产(小米/氢氧/锤子)
具体版本: 
Android 8.0.0 EMUI 8.0.0
## 您使用的cimoc版本
V1.4.33（412）

**Comment by feilongfl** [comment]
这个网站好有意思，丧心病狂aes加密，然后把密码写在了旁边2333

**Comment by Steve-337** [comment]
@feilongfl 更新后闪退了，还有tachiyomi那头什么时候修复一下？

**Comment by feilongfl** [comment]
tachiyomi先更新的,已经可以用了

**Comment by feilongfl** [comment]
我去检查下自动集成,最近travis的安卓编译策略换了

**Comment by feilongfl** [comment]
已修

**Comment by Laxwei** [comment]
呃，又是我。漫画堆图源所有漫画第一页都解析错误显示不出来

**Comment by feilongfl** [comment]
> 呃，又是我。漫画堆图源所有漫画第一页都解析错误显示不出来

已修,这个问题是我把tachiyomi的代码粘过来时候没主意两边的处理过程不一样,那边是直接进js解释器了,这边是正则

**Comment by Steve-337** [comment]
@feilongfl tachiyomi那边的漫画堆存在部分章节缺失的问题，cimoc有但tachiyomi里面就没有

**Comment by Laxwei** [comment]
tachiyomi怎么用，能教教我吗？

**Comment by feilongfl** [comment]
@Laxwei 额，这个不至于吧
就是安装之后去拓展里面选漫画源，然后去分类里面选中文

**Comment by feilongfl** [comment]
@Steve-cn :disappointed_relieved: 这个...举个例子呗

**Comment by Laxwei** [comment]
会了，谢谢

**Comment by Laxwei** [comment]
@feilongfl 谢谢，懂了

**Comment by Steve-337** [comment]
@feilongfl 为什么老师会在这里https://m.manhuadui.com/manhua/weishimelaoshihuizaizheli/
在cimoc里面就有番外，但在tachiyomi里面就没有番外（话说comic里面还是无法下载这个漫画，tachiyomi倒是正常）

算了，我放弃在漫画堆里面看了，动漫之家有
