### ISSUE TITLE
魅族16用新版本会白屏进不去

### ISSUE THREAD

**Issue by Laxwei** [feilongfl/Cimoc#149]
![S90621-09355806](https://user-images.githubusercontent.com/50709024/59891518-faac9c00-93c4-11e9-8824-0fa5d69e20a8.png)
这是怎么回事？出bug了

**Comment by feilongfl** [comment]
恩,自动集成貌似有问题
https://github.com/feilongfl/Cimoc/issues/148

**Comment by Laxwei** [comment]
那怎么解决咧

**Comment by feilongfl** [comment]
刚才光顾着找问题来着,忘了把有问题的版本撤回来了

**Comment by feilongfl** [comment]
正在找问题在哪

**Comment by Laxwei** [comment]
辛苦你了

**Comment by Laxwei** [comment]
？怎么了？

**Comment by feilongfl** [comment]
现在好了

**Comment by Laxwei** [comment]
辛苦了
