### ISSUE TITLE
搜索结果中不显示来自看漫画源的结果

### ISSUE THREAD

**Issue by ZheiZhei** [feilongfl/Cimoc#150]
# 这是一个漫画源问题

2019年6月21日下午起搜索结果中不显示来自看漫画源的结果，无论目标漫画是否在中国地区遭到下架。同日凌晨1.4.35版本搜索结果正常，但现1.4.35版本也无法显示搜索结果，排除软件版本原因。现看漫画网页版在特定ip地址下可显示全部搜索结果，疑网站搜索规则有所变化。

## 出现错误的漫画源

看漫画 (manhuagui.com)

## 您搜索/观看的漫画名称或关键字以及访问链接

怪怪守护神 (https://www.manhuagui.com/comic/1011/)

## 在以下环节中出现错误
- [X] 搜索
- [ ] 章节信息
- [ ] 图片加载

## 你是否使用科学上网工具
- [X] 是
- [ ] 否

## 你是否能够访问漫画源网页并成功加载漫画图片
- [X] 是
- [ ] 否

在特定ip地址下网页版和软件历史收藏内均可成功加载漫画。

## 您手机的系统版本
- [ ] 原生(AOSP/LL/RR/Mokee等)
- [X] 国产(小米/氢氧/锤子)
具体版本: 经测试系统版本与该问题无关。

## 您使用的cimoc版本
V1.4.36 (432)

**Comment by Steve-cn** [comment]
看漫画不是被屏蔽了吗？我用站长工具ping了一下所有国内的运营商都是超时

**Comment by hzbr** [comment]
我更新了1.4.37后还是打不开也搜索不到漫画柜的源

**Comment by wrlssqi** [comment]
最近似乎漫画柜使用科学上网反而会无响应，直连能打开。。。

**Comment by hzbr** [comment]
> 最近似乎漫画柜使用科学上网反而会无响应，直连能打开。。。

能打开和搜索，可是图片加载不出来。
