### ISSUE TITLE
[CS] 添加 90漫画 源

### ISSUE THREAD

**Issue by mzji** [feilongfl/Cimoc#152]
规则已经写好，但是不会用 git ，哪位大佬帮忙把代码凑一下，辛苦了

getSearchRequest:
`http://www.90mh.com/search/?keywords=%s` ，`UTF-8` 编码，没观察到分页
getSearchIterator:
上面的搜索返回的页面，parse 之后用这条 query 规则 `#contList.book-list > li.item-lg` 能找到多个 `li` 元素，每一个是一个漫画搜索结果
　　cover: 漫画搜索结果 `li` 元素里面的第一个 `img` 元素的 `src` 属性，是全路径
　　title: cover 对应的 `img` 元素的 `alt` 属性的文本
　　update: 漫画搜索结果 `li` 元素里面，用这个 query 规则 `span.updateon` 找到的第一个 `span` 元素的 `innerText` 属性，取 `substring(4)`
　　cid: 上面找到的单个 `li` 元素里，用这个 query 规则 `p.ell a` 找到的第一个 `a` 元素的 `href` 属性，是每部漫画的页面，全路径，直接拿漫画页面的 url 作为 cid

getUrl: 直接用 cid
getInfoRequest: 直接用 cid
parseInfo: 打开 cid 获取 html ，parse 之后：
　　cover: 用这个 query 规则 `div.book-cont div.book-cover p.cover img` 找到的第一个 `img` 元素的 `src` 属性
　　title: cover 对应的 `img` 元素的 `alt` 属性的文本
　　update: 用这个 query 规则 `div.book-cont div.book-detail li.status span span` 找到的第一个 `span` 元素的 `innerText` 属性
　　author: 用这个 query 规则 `div.book-cont div.book-detail li:nth-child(2) span:nth-child(2) a` 找到的第一个 `a` 元素的 `innerText` 属性
　　status: 用这个 query 规则 `div.book-cont div.book-detail li.status span a:first-of-type` 找到的第一个 `a` 元素的 `innerText` 属性，如果为 `连载中` 则是正在连载

parseChapter: 打开 cid 页获取 html ，parse 之后用这个 query 规则 `div.comic-chapters > div.chapter-body > ul#chapter-list-10 li` ，能找到多个 `li` 元素，每一个是一个章节
　　title: 章节对应的 `li` 元素中，找第一个 `span` 元素，它的 `innerText` 属性是章节标题
　　path: 章节对应的 `li` 元素中，找第一个 `a` 元素，它的 `href` 属性是章节路径（全路径）

getImagesRequest: 直接用章节的 `path` 获取页面
parseImages: 拿到章节的页面后：
　　获取每页图像的文件名：
　　　　直接搜索章节页面的 html 字符串（不需要进行解析），寻找 `var chapterImages = [` 及紧跟它之后的 `];` （用 indexOf 就可以），取中间部分字符串，用 `,` 作为分隔符进行分割，得到的每一段去除两端的 `"` 符号，可得到所有页面图像的文件名列表
　　获取图像的相对路径：
　　　　直接搜索章节页面的 html 字符串（不需要进行解析），寻找 `var chapterPath=` 及紧跟它之后的 `;` （用 indexOf 就可以），取中间部分字符串，去除两端的 `"` 符号，得到图像的相对路径
　　图像存储服务器： `http://img.xmhjtx.com`
　　图像的绝对路径：拼接字符串：服务器 + 相对路径 + 文件名，得到图像绝对路径的字符串
　　页面图像获取过程中不要求 cookie 或 referrer

**Comment by feilongfl** [comment]
要是能直接写成java就更好了

![ezgif-2-0757c889b236](https://user-images.githubusercontent.com/10269596/60375726-3d154f00-9a3d-11e9-9aa0-613062c99968.jpg)

**Comment by mzji** [comment]
> 要是能直接写成java就更好了

俺不会 Java 呀……手上也没有 Java 环境，更不想装
