### ISSUE TITLE
能不能请作者检查一下这是哪里出了问题

### ISSUE THREAD

**Issue by ckn4** [feilongfl/Cimoc#154]
tachiyomi还是用不习惯，靠着cimoc勉强过过日子。
自己简单给yyls这个网站写了个规则，在线看没有问题。
问题出在下载，下载过程也没有问题，查找文件夹也出现了下载漫画的图片，并且图片可以正常打开，但是在软件里下载管理打开下载下来的漫画却提示解析错误。
我找了好久也没有找到问题出在哪里，不知道作者能不能帮忙检查一下。（规则基于原始版本，稍微修改下就能在你修改的版本上用。）
[Yyls.txt](https://github.com/feilongfl/Cimoc/files/3348294/Yyls.txt)

**Comment by feilongfl** [comment]
已经merge
