### ISSUE TITLE
漫画柜又挂了

### ISSUE THREAD

**Issue by yybzckl** [feilongfl/Cimoc#156]

**Comment by Mortalit** [comment]
+1 网页版能打得开,app一直解析失败

**Comment by GodSavior** [comment]
感觉是因为IP的关系...用着wifi刚打开app可以用，可是扫描更新或者下载几分钟之后就连突然不上了...挂了VPN之后又好了，不过几分钟之后又会出问题...无限循环

**Comment by feilongfl** [comment]
我用着挺正常的啊,难道是我漫画看得太少了?

**Comment by GodSavior** [comment]
这还真有可能，可能是超过一定的流量才会被暂时封ip吧，可不可以试着添加一下台湾繁体版的漫画柜，听说比较稳

**Comment by ChloeKurumi** [comment]
> 我用着挺正常的啊,难道是我漫画看得太少了?

应该是使用第三方软件被检测到了，被屏蔽ip了。。。。。。我试过，用某个能打开网站的节点通过app看漫画柜，一会儿ip就被封了，连网站都打不开了。。。。顺便一提。。。。我ip全部被屏蔽了，现在连网站都不能正常访问。。。。。

**Comment by Mortalit** [comment]
好像就是封了用app看的ip,找了3个节点能用的,在手机上看了会,再过了几小时再看就解析失败了

**Comment by Mortalit** [comment]
找了几个能用的节点试了一下,用app看漫画柜,大概两三个小时后该节点就会被封,用电脑看就不会

**Comment by ChloeKurumi** [comment]
> 找了几个能用的节点试了一下,用app看漫画柜,大概两三个小时后该节点就会被封,用电脑看就不会

我直接就是秒封啊。。。。只要用app访问一次，就再也进不了网站了。。。。。早上都还能打开网站，我就打开了下Cimoc，结果过一会儿就打不开网站了。。。。明明连漫画都没点开。。。。难道说之前收藏的漫画柜漫画在载入封面的时候也算在内？

**Comment by 3MMMing** [comment]
我覺得可能是app或者漫畫櫃他們設定的問題，因為當我使用自己的網路被封鎖後，大約一個禮拜就突然解開可以繼續看，可是看了1.2小時候又被封鎖，等下次解開後再用手機瀏覽器來試試看會不會被封鎖好了🤔

**Comment by ChloeKurumi** [comment]
> 我覺得可能是app或者漫畫櫃他們設定的問題，因為當我使用自己的網路被封鎖後，大約一個禮拜就突然解開可以繼續看，可是看了1.2小時候又被封鎖，等下次解開後再用手機瀏覽器來試試看會不會被封鎖好了🤔

看了下终于解封了，不是永封我就放心了。。。。就是不知道封多久，总之上周一周都各种打不开。。。。。。不敢用app看了，站长都说了用第三方会封ip，就是不说封多久。。。。
