### ISSUE TITLE
在看腾讯动漫的一人之下时候，收费章节只能看到一页。

### ISSUE THREAD

**Issue by ghost** [feilongfl/Cimoc#16]
翻页模式下点下一页直接跳到下一章了。而且右上角显示一页。

**Comment by feilongfl** [comment]
本程序并没有集成任何破解功能
@yiyebai

**Comment by ghost** [comment]
> 本程序并没有集成任何破解功能
> @yiyebai

嗯……后来对比才发现是收费章节出现问题，所以关闭了issue。
