### ISSUE TITLE
古风漫画出问题了

### ISSUE THREAD

**Issue by PatrickW-zh** [feilongfl/Cimoc#164]
# 这是一个漫画源问题

> 请您在提交本问题前仔细完成下面问题以便更好地解决问题.
> 如果有多个漫画源出错，请不要合并在一起，谢谢

## 出现错误的漫画源
古风漫画
## 您搜索/观看的漫画名称或关键字以及访问链接
《嗜谎之神》
https://m.gufengmh8.com/manhua/shihuangzhishen/
## 在以下环节中出现错误
- 章节信息（提示解析错误，显示不出章节）

## 你是否使用科学上网工具
- 否（都试过）

## 你是否能够访问漫画源网页并成功加载漫画图片
- 是

## 您手机的系统版本
- 国产(小米/氢氧/锤子)
具体版本: Huawei EMUI 9.0.0

## 您使用的cimoc版本
V1.4.38(436)

**Comment by feilongfl** [comment]
我刚才试了一下,这个网页打不开漫画啊...

不过有个地方确实匹配有问题,修了
