### ISSUE TITLE
希望增加 满画楼 https://www.manhualou.com/

### ISSUE THREAD

**Issue by mabDc** [feilongfl/Cimoc#168]
[满画楼](https://www.manhualou.com/) 资源质量不错，规则也简单，它的发现和搜索可以共用一个解析方法，图源可以参考
[ManHuaLou.kt](https://github.com/mabDc/Meow/blob/feature/refactor/app/src/main/java/top/rechinx/meow/core/source/internal/ManHuaLou.kt) (做给 [Meow](https://github.com/neverfelly/Meow) 用的，规则大概是 [tachiyomi](https://github.com/inorichi/tachiyomi) 的简易版)

**Comment by mabDc** [comment]
给喵呜加了土豪漫画源，发现详情页加载好久，tachiyomi 里的土豪漫画也慢么？
（上传了一个更新版 https://github.com/mabDc/Meow/releases/latest

**Comment by feilongfl** [comment]
最近在搬家，刚把电脑拼上，还缺显示器:joy:

土豪的tachiyomi不是我做的，试了一下速度没什么问题

**Comment by mabDc** [comment]
加漫画源可以参考这个文件夹，有几个cimoc没有或不一样的（漫画楼、DongMan、bilibili、ManHuaTai、Tencent
https://github.com/mabDc/Meow/blob/feature/refactor/app/src/main/java/top/rechinx/meow/core/source/internal/
