### ISSUE TITLE
关于安卓8.0+的通知频道设置问题导致检测更新时通知一直在响的BUG

### ISSUE THREAD

**Issue by zhihaofans** [feilongfl/Cimoc#17]
检测更新时的通知请使用静音频道，要不然通知会一直响

![Screenshot_20181114-170656_Settings.jpg](https://i.loli.net/2018/11/14/5bebe60549aa9.jpg)

**Comment by feilongfl** [comment]
以前注意过这个问题，不过手机上可以直接设置静音，就没改😄

**Comment by zhihaofans** [comment]
@feilongfl 还有要是能保存漫画的某一张图片就好了

**Comment by feilongfl** [comment]
声音问提修复在
https://github.com/feilongfl/Cimoc/commit/e24f05e0b96c661580ecb9cf7e44995c0daa310f
未实际测试

**Comment by feilongfl** [comment]
apk文件
https://github.com/feilongfl/Cimoc/releases/tag/v1.4.8.8054-notif-test

**Comment by feilongfl** [comment]
@zhihaofans 试一下,有问题我再处理

**Comment by zhihaofans** [comment]
@feilongfl 你好，更新了`v1.4.8.8054`后通知频道没问题了，但是出现继续阅读按钮图标错位的bug，我在三星s8+(Android 8.0，更新)和Nokia x6(Android 9.0，新安装该应用)都出现该问题（如下图），Nokia x6(Android 9.0)使用时还出现`动漫之家v2`解析失败(三星的没问题)


![https://ws3.sinaimg.cn/large/006tNbRwgy1fxq18jaophj30u01pogq3.jpg](https://ws3.sinaimg.cn/large/006tNbRwgy1fxq18jaophj30u01pogq3.jpg)

**Comment by zhongfly** [comment]
> @feilongfl 你好，更新了`v1.4.8.8054`后通知频道没问题了，但是出现继续阅读按钮图标错位的bug，我在三星s8+(Android 8.0，更新)和Nokia x6(Android 9.0，新安装该应用)都出现该问题（如下图），Nokia x6(Android 9.0)使用时还出现`动漫之家v2`解析失败(三星的没问题)
> 
> ![https://ws3.sinaimg.cn/large/006tNbRwgy1fxq18jaophj30u01pogq3.jpg](https://camo.githubusercontent.com/97a09f066a2ab0e1e288c6fa20ed90d79f08bd70/68747470733a2f2f7773332e73696e61696d672e636e2f6c617267652f303036744e62527767793166787131386a616f70686a3330753031706f6771332e6a7067)

8048版本未出现，8054版本也出现了同样图标错位的问题
Android7.1.2（8048更新至8054）

**Comment by feilongfl** [comment]
图标错位已记录，争取下个版本修复

**Comment by feilongfl** [comment]
fixed at https://github.com/feilongfl/Cimoc/releases/tag/v1.4.8.8055
