### ISSUE TITLE
[CS]动漫屋源解析错误

### ISSUE THREAD

**Issue by maiweijin** [feilongfl/Cimoc#171]
# 这是一个漫画源问题

> 请您在提交本问题前仔细完成下面问题以便更好地解决问题.
> 如果有多个漫画源出错，请不要合并在一起，谢谢

## 出现错误的漫画源
动漫屋

## 您搜索/观看的漫画名称或关键字以及访问链接
关于我的房间成为了地下城的休息点的事情

## 在以下环节中出现错误
- [ ] 搜索
- [ V] 章节信息
- [ ] 图片加载

## 你是否使用科学上网工具
- [V ] 是
- [ ] 否

## 你是否能够访问漫画源网页并成功加载漫画图片
- [ V] 是
- [ ] 否
能通过漫画人App搜索并打开对应漫画

## 您手机的系统版本
- [ ] 原生(AOSP/LL/RR/Mokee等)
- [V ] 国产(小米/氢氧/锤子)
具体版本: MIUI 10.3 安卓版本8.1.0 型号MI 5X

## 您使用的cimoc版本
V1.4.38

**Comment by feilongfl** [comment]
网站无法打开指定漫画

![image](https://user-images.githubusercontent.com/10269596/63630647-af766a00-c64f-11e9-93b6-2fab0e5eee23.png)
