### ISSUE TITLE
[CS]漫画堆

### ISSUE THREAD

**Issue by 985907154** [feilongfl/Cimoc#172]
# 这是一个漫画源问题

> 请您在提交本问题前仔细完成下面问题以便更好地解决问题.
> 如果有多个漫画源出错，请不要合并在一起，谢谢

## 出现错误的漫画源
漫画堆
## 您搜索/观看的漫画名称或关键字以及访问链接
总之就是非常可爱
https://www.manhuadui.com/manhua/zongzhijiushifeichangkeaiflymetothemoon/
## 在以下环节中出现错误
图片加载
## 你是否使用科学上网工具
 否

## 你是否能够访问漫画源网页并成功加载漫画图片
是

## 您手机的系统版本
国产(小米/氢氧/锤子)
具体版本: 小米8探索版 系统：miui 10.3.5

## 您使用的cimoc版本
V1.4.38（436）

**Comment by mzji** [comment]
漫画堆更换了图片服务器，目前的图片服务器是 `https://mhcdn.manhuazj.com`

**Comment by Laxwei** [comment]
那怎么操作咯。。。

**Comment by mzji** [comment]
需要改代码重新编译
https://github.com/feilongfl/Cimoc/blob/release-tci/app/src/main/java/com/hiroshi/cimoc/source/MH50.java#L132..L136
这个数组里面的内容替换为
```java
"https://mhcdn.manhuazj.com"
```

**Comment by Laxwei** [comment]
怎么修改。。。我不会打开编码。。

**Comment by mzji** [comment]
呃，我这里也没工具啊……

**Comment by feilongfl** [comment]
ref:
https://github.com/feilongfl/Cimoc/pull/184
