### ISSUE TITLE
[CS]漫画堆换源

### ISSUE THREAD

**Issue by Johnnysama** [feilongfl/Cimoc#175]
# 这是一个漫画源问题

> 请您在提交本问题前仔细完成下面问题以便更好地解决问题.
> 如果有多个漫画源出错，请不要合并在一起，谢谢

## 出现错误的漫画源
漫画堆
## 在以下环节中出现错误
- [ ] 搜索
- [ ] 章节信息
- [ √] 图片加载

## 你是否使用科学上网工具
- [ ] 是
- [√ ] 否

## 你是否能够访问漫画源网页并成功加载漫画图片
- [ √] 是
- [ ] 否

## 您手机的系统版本
- [ ] 原生(AOSP/LL/RR/Mokee等)
- [√ ] 国产(小米/氢氧/锤子)
具体版本: 
红米4X
## 您使用的cimoc版本
V1.4.8.8xxx

**Comment by Johnnysama** [comment]
新源是https://mhcdn.manhuazj.com

**Comment by feilongfl** [comment]
重复https://github.com/feilongfl/Cimoc/issues/172
