### ISSUE TITLE
软件问题相关

### ISSUE THREAD

**Issue by jczh98** [feilongfl/Cimoc#176]
事实上tachiyomi在泛化性上已经做得足够优秀了，可是在一些国内外差异上依旧还是不如comic的体验
作者有考虑过fork一份tachiyomi或者完全重写一套吗

**Comment by feilongfl** [comment]
2333
tachiyomi他们已经在缓慢的重写中了~~

**Comment by jczh98** [comment]
1.x的代码更像是实验性质的重写，感觉一年都合不进主线23333
tachiyomi或者cimoc的源也不容易扩展到跨平台orz

**Comment by saasddsaasdd** [comment]
个人角度，tachiyomi在阅读功能上还是有所欠缺，比如不能对单页进行自动双页切割，比如阅读时不能选择显示文件名或者时间，目前还不足取代cimoc
