### ISSUE TITLE
一直顯示讀取數據失敗

### ISSUE THREAD

**Issue by shenkyw** [feilongfl/Cimoc#177]
新安裝一打開就一直在下方顯示讀取數據失敗，允許儲存權限後也還是一樣，搜尋後點任何結果又會跳回搜尋頁面，作任何操作都不會有資料出現，打開 Cimoc 資料夾內可以看到錯誤紀錄如下

MODEL: R08N
SDK: 23
RELEASE: 6.0.1

Unable to start activity ComponentInfo{com.hiroshi.cimoc/com.hiroshi.cimoc.ui.activity.DetailActivity}: android.database.sqlite.SQLiteException: no such column: T.URL (code 1): , while compiling: SELECT T."_id",T."SOURCE",T."CID",T."TITLE",T."COVER",T."HIGHLIGHT",T."LOCAL",T."UPDATE",T."FINISH",T."FAVORITE",T."HISTORY",T."DOWNLOAD",T."LAST",T."PAGE",T."CHAPTER",T."URL" FROM "COMIC" T  WHERE T."SOURCE"=? AND T."CID"=?

android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2427)
android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2487)
android.app.ActivityThread.-wrap11(ActivityThread.java)
android.app.ActivityThread$H.handleMessage(ActivityThread.java:1352)
android.os.Handler.dispatchMessage(Handler.java:102)
android.os.Looper.loop(Looper.java:148)
android.app.ActivityThread.main(ActivityThread.java:5431)
java.lang.reflect.Method.invoke(Native Method)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:772)
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:662)

**Comment by feilongfl** [comment]
这个也是博阅?
试一下测试版,看下https://github.com/feilongfl/Cimoc/pull/163 有没有修复

**Comment by shenkyw** [comment]
是 Hyread Gaze, 但我猜底層就是博阅
更新後可以使用了，感謝
