### ISSUE TITLE
在淘宝上有人在倒卖

### ISSUE THREAD

**Issue by xiaou66** [feilongfl/Cimoc#181]
最近我偶然发现淘宝有人在倒卖这个软件，希望作者可以加个免费提示

例如这家
【哔哩哔哩漫画破解版VIP会员免漫币网易漫画快看漫画APP布卡漫手绘】https://m.tb.cn/h.eQVIbkG?sm=294db2 点击链接，再选择浏览器咑閞；或椱ァ製这段描述₤Lo9hYjFaI0F₤后到👉◇綯℡寳👈

**Comment by xiaou66** [comment]
避免再有人上当受骗

**Comment by mokurin000** [comment]
有没有给出获取源码的途径……
我记得GPL允许出售的

**Comment by mokurin000** [comment]
GPL还规定，经销商不得对GPL授予的权利施加“进一步限制”。禁止根据不披露协议或合同分发软件等活动。 ——维基百科，遵循CC-BY-SA 3.0转载

**Comment by mokurin000** [comment]
刚刚去联系了，现在销售商声称待作者的联系

**Comment by zhongfly** [comment]
这种都是在骗傻子钱，联系店家肯定没用，直接找淘宝处理吧。

**Comment by mokurin000** [comment]
> 
> 
> 这种都是在骗傻子钱，联系店家肯定没用，直接找淘宝处理吧。

淘宝看过了，需要作者本人实名举报

**Comment by mokurin000** [comment]
> 
> 
> 这种都是在骗傻子钱，联系店家肯定没用，直接找淘宝处理吧。

又或者是任何人实名举报…… 没写明

**Comment by feilongfl** [comment]
实名举报...真是够有特色的,浪费精力还没什么用
