### ISSUE TITLE
手机报毒

### ISSUE THREAD

**Issue by QZBT** [feilongfl/Cimoc#183]
华为手机.官方emui9.1系统.一直会报风险.很奇怪.
![阴影20190817-234022](https://user-images.githubusercontent.com/48495382/63214268-b6c9df00-c148-11e9-8672-3960a5c1e282.png)
用是能用.经常询问挺烦的.

**Comment by feilongfl** [comment]
参考https://github.com/feilongfl/Cimoc/issues/132
