### ISSUE TITLE
每次看的时间一久就会闪退

### ISSUE THREAD

**Issue by blackacrow** [feilongfl/Cimoc#187]
手机华为，其实不太清楚是看得太多会闪退还是时间问题。因为看的速度快一点，也会闪退。

**Comment by mokurin000** [comment]
看看内存占用？（ 不清楚…… 我的EEBBK S2 (2G)没出现过

**Comment by ckn4** [comment]
如果是华为手机的话，基本上是因为超过了华为的进程限制（只有500），提问这些问题的时候，建议提供Log

**Comment by feilongfl** [comment]
手里唯一的华为手机年初时候被我弄挂了 😭 
目前手里只有原生可以调试...
