### ISSUE TITLE
关于cimoc软件版权问题请飞龙看一下

### ISSUE THREAD

**Issue by zaitian-ziv** [feilongfl/Cimoc#188]
感谢飞龙先生

**Comment by zaitian-ziv** [comment]
这是我的q1355013550希望能跟飞龙先生取得联系

**Comment by Beer-125** [comment]
希望你获得的利润能和作者谈清楚。GitHub上大多数人都是秉承着开源免费的思想，希望和大家共同进步，而绝不是拿去盈利。最后希望能和作者谈好，不要惹出麻烦。

**Comment by mokurin000** [comment]
嗯…… 我自己看来这不是一个破解软件。它只是爬取各个平台，自行解析并绘制，而不是修改其他平台的应用。 GPL下允许售卖，但请表明许可证等。

**Comment by pffang** [comment]
把不当牟利说得这么冠冕堂皇理直气壮还真是厉害了，我差点就信了。

**Comment by zaitian-ziv** [comment]
别，我求您别信，我就是一个坏人

**Comment by mokurin000** [comment]
请您发布软件副本时附带源代码；
请写明许可证（商品简介）。
我并没有详看过GPLv3，下面请各位大佬写一下还有什么要求了

**Comment by mokurin000** [comment]
> 
> 
> 请您发布软件副本时附带源代码；
> 请写明许可证（商品简介）。
> 我并没有详看过GPLv3，下面请各位大佬写一下还有什么要求了

因为GPL v3允许指明得到源码的“清晰方向”
所以请至少写明该软件在GPLv3下发布

**Comment by zaitian-ziv** [comment]
小飞，你咋还不出现呢？我等你好久了

**Comment by PPPTK318** [comment]
真的多得你们这些无良js，乱传就算了还卖钱，而且这么高调，现在还跑来立牌坊，说得多么富丽堂皇，最后还是想着拿去卖钱，app能不能活下去也就作者的一个决定，到时候还真的是要烧高香谢谢你们了

**Comment by zaitian-ziv** [comment]
骂的真好，给你点赞了！

**Comment by ParanoiaIsGreat** [comment]
卖的人又当又立，卖的人也是憨憨

**Comment by mokurin000** [comment]
怎么说…… GPL许可证允许贩卖软件，但是请遵循要求而不是直接拿去卖
开源不等于免费的 虽然开源的话也可能允许你自行编译

**Comment by mokurin000** [comment]
作者大概懒得理睬这些事吧emm

**Comment by zaitian-ziv** [comment]
请问这个帖子如何删除呢

**Comment by zaitian-ziv** [comment]
我找不到删除的按钮

**Comment by zaitian-ziv** [comment]
poly000你出来下

**Comment by mokurin000** [comment]
> 
> 
> poly000你出来下

看来只有 [feilong](https://github.com/feilong) 有删除权限

**Comment by zaitian-ziv** [comment]
想哭

**Comment by mokurin000** [comment]
> 
> 
> 想哭

请在商品简介写明许可证或者提供许可证的链接：
https://raw.githubusercontent.com/feilongfl/Cimoc/release-tci/LICENSE.md

**Comment by mokurin000** [comment]
> 
> 
> 想哭

GPL允许出售GPL作品，但是不允许限制GPL授予用户的权利，禁止不披露协议分发软件。

**Comment by mokurin000** [comment]
[shop591419729](https://shop591419729.taobao.com)
请问您是这家店店主吗？……
像前面说的，请写明该软件在 __[此协议](https://raw.githubusercontent.com/feilongfl/Cimoc/release-tci/LICENSE.md)__ 下发布。
如果不是，可能只是凑巧…… 那样我刚提醒的那位就人间蒸发或者以其他方式联系feilong了
不过有免费下载渠道的还去买，而且购买并不会支持作者…… 这样的人可能很少了

**Comment by zaitian-ziv** [comment]
感谢

**Comment by mokurin000** [comment]
> 
> 
> 感谢

nevermind

**Comment by feilongfl** [comment]
希望能够遵守许可证分发
