### ISSUE TITLE
调整下拉阅读模式

### ISSUE THREAD

**Issue by tjikaros** [feilongfl/Cimoc#192]
有些漫画把正常的一页切成了几页，比如漫画 我身上有条龙 古风漫画源。目前的下拉方式不是滑动下拉，是翻页的模式，这样看起来每一页只能看到完整一页的一小半。希望能调整成滑动式无缝衔接的下拉阅读模式，比如腾讯动漫那种滑动下拉模式

**Comment by gameclamp** [comment]
在设置里用卷纸模式就是你说的下拉模式
