### ISSUE TITLE
下载界面右下角的按钮按不到

### ISSUE THREAD

**Issue by trim21** [feilongfl/Cimoc#2]
Android 7.1.2
API 25
Rom是LineageOS

![screenshot_20180409-195000](https://user-images.githubusercontent.com/13553903/38496282-8761ff1c-3c2f-11e8-8068-bd617fa65370.png)

这个按钮按下去的话会点到底层的漫画章节
![image](https://user-images.githubusercontent.com/13553903/38496290-90d57d6c-3c2f-11e8-83f4-f14839e5a16b.png)
右上角有一个相同图标的按钮可以点,似乎是用来继续阅读的

**Comment by feilongfl** [comment]
这个位置正常不是这样子的...你检查下版本是不是最新的

这是我的这个界面
android mokee 8.1
cimoc v1.4.8.8041
![photo_2018-04-09_21-38-21](https://user-images.githubusercontent.com/10269596/38500938-564658e2-3c3e-11e8-956c-913cea7f2c50.jpg)

如果是最新的希望你能够告诉我你这个是怎么弄出来的😄

**Comment by trim21** [comment]
是最新的...1.4.8.8041
先往下一拉,隐藏右下角的按钮,然后再往上一拉让右下角的按钮显示出来,就会显示两个按钮- -

**Comment by feilongfl** [comment]
在我的记忆里面这个界面没加过啊😰看来可能是什么时候不小心改错了，顺便我下载功能用的不多没发现😭争取下个版本修复

**Comment by feilongfl** [comment]
fixed in v1.4.8.8042

https://github.com/feilongfl/Cimoc/releases/tag/v1.4.8.8042
