### ISSUE TITLE
"操作失败"

### ISSUE THREAD

**Issue by GodSavior** [feilongfl/Cimoc#20]
为什么点击"看漫画"，"E-Hxxxxx"等插件时会提示操作失败?

**Comment by GodSavior** [comment]
[
![screenshot_cimoc_20181130-120324](https://user-images.githubusercontent.com/19355470/49268067-54d12880-f498-11e8-9440-8fdccd7f6651.png)
](url)

**Comment by feilongfl** [comment]
这个版本刚编译好,我还没试呢😅

**Comment by feilongfl** [comment]
我记得ehentai貌似有点问题,还没修复,简单看了下代码,应该是我适配的源没实现这个功能(之前我都没注意这里还能点开,怎么看都只是开关啊😅所以只做了正常搜索的部分)

**Comment by ParanoiaIsGreat** [comment]
> 我记得ehentai貌似有点问题,还没修复,简单看了下代码,应该是我适配的源没实现这个功能(之前我都没注意这里还能点开,怎么看都只是开关啊所以只做了正常搜索的部分)

我从8052更到8053后，几乎所有都是解析失败（绝大部分动漫之家）。。。
然后退回8052就又正常。。

**Comment by feilongfl** [comment]
不应该吧,默默表示我没改动漫之家源啊,我去试试

**Comment by ParanoiaIsGreat** [comment]
> 不应该吧,默默表示我没改动漫之家源啊,我去试试

8052到8054后也是一样。。

**Comment by feilongfl** [comment]
8052修改了漫画柜,8053适配了安卓9修正了腾讯动漫,8054只修改了通知啊,而且8052是8月份发布的,我一直在用啊
我指的`动漫之家v2`,之前动漫之家有两个(`动漫之家`,和`动漫之家v2`),应该都是原作作者留下的,不知道为什么有两个,后来貌似是有一套api被废弃掉了,所以我只维护了`动漫之家v2`

**Comment by feilongfl** [comment]
我试了一下`动漫之家v2`最新版本可以用的

**Comment by ParanoiaIsGreat** [comment]
> 8052修改了漫画柜,8053适配了安卓9修正了腾讯动漫,8054只修改了通知啊,而且8052是8月份发布的,我一直在用啊
> 我指的`动漫之家v2`,之前动漫之家有两个(`动漫之家`,和`动漫之家v2`),应该都是原作作者留下的,不知道为什么有两个,后来貌似是有一套api被废弃掉了,所以我只维护了`动漫之家v2`

那就很迷了。。-. - 我这边8052一切正常，8054试了卸载重安还是解析错误。。

**Comment by feilongfl** [comment]
你试的什么漫画啊,我是随便搜索的

**Comment by ParanoiaIsGreat** [comment]
> 你试的什么漫画啊,我是随便搜索的

你试试：婚戒物语、舞动青春、狂赌之渊？
我用8052是可以的，8054解析错误。。

**Comment by feilongfl** [comment]
试过了,没问题啊
录了个视频
https://cuntuku.com/image/bASue

**Comment by GodSavior** [comment]
我这里动漫之家正常

**Comment by ParanoiaIsGreat** [comment]
> 试过了,没问题啊
> 录了个视频
> https://cuntuku.com/image/bASue

很迷。。不纠结了。。等后面版本再看看。。

**Comment by feilongfl** [comment]
隔壁issue老哥两个手机一个正常一个有问题:sob:，我回头再试试吧

**Comment by zhongfly** [comment]
关于动漫之家源，我也觉得有问题，有些漫画必须开启或关闭梯子 才能打开或阅读漫画，然而检测更新时都能检测到更新，就很迷（也有可能是梯子里代理规则的问题就是了）

**Comment by Hinotori1127** [comment]
圖源裡面有一些源點擊會出現操作失敗 動漫之家我這裡沒問題

**Comment by Rugg3** [comment]
魅蓝note5备份显示操作失败

**Comment by feilongfl** [comment]
@Rugg3 试了一下mokee8备份正常，我没有魅族📱，所以 :sweat: ，你可以检查一下存储权限，app就要了这一个权限

**Comment by Rugg3** [comment]
@feilongfl 重置手机然后发现可以了
