### ISSUE TITLE
一些建议

### ISSUE THREAD

**Issue by asuka13eva** [feilongfl/Cimoc#200]
首先再次给fl大佬和APP开发者们递茶。。
使用一段时间之后感觉有如下几点可以优化：
1、收藏页增加排序方式（例如：添加收藏时间，更新时间，名称，漫画源等）
2、漫画列表页内排序方式（例如：漫画堆。番外和单行本和连载排序方式错误，导致某些番外永远在最前面，更新的一话排在番外后面）
3、漫画列表页内文字显示（例如：997700，第X话前有漫画名，导致漫画名都显示不完全，想看某话得数数）

（弱气）大佬不改也没事儿……做不出什么贡献的我其实有的用就行了……还是漫画源的修复、追加和更新更重要……请你们自觉保护肝脏……

**Comment by Steve-337** [comment]
fl向tachiyomi转移了，所以还是建议用tachiyomi，当然这个漫画源更多，那个使用体验更好，可以两个互补使用

**Comment by feilongfl** [comment]
确实是在向tachiyomi转移，漫画源感觉用的多的都转过去了，我抽时间看看剩下那些比较有用的也转移一下，功能上这边不打算有太大修改了，因为tachiyomi那边维护的人更多一些，功能也很齐全，虽然release速度慢一些，但是仓库里面的代码大家都可以自己编译

**Comment by aawwsslll** [comment]
> 确实是在向tachiyomi转移，漫画源感觉用的多的都转过去了，我抽时间看看剩下那些比较有用的也转移一下，功能上这边不打算有太大修改了，因为tachiyomi那边维护的人更多一些，功能也很齐全，虽然release速度慢一些，但是仓库里面的代码大家都可以自己编译

tachiyomi想看生肉或者其他的语言的漫画优势很大，基本是语言最全的插件漫画网站了，而且现在中文也有10来个插件，基本都够用了。

**Comment by aawwsslll** [comment]
> 确实是在向tachiyomi转移，漫画源感觉用的多的都转过去了，我抽时间看看剩下那些比较有用的也转移一下，功能上这边不打算有太大修改了，因为tachiyomi那边维护的人更多一些，功能也很齐全，虽然release速度慢一些，但是仓库里面的代码大家都可以自己编译

顺便那边有人提中文插件开发请求。大佬你有时间可以去看看有哪些中文网站适合做插件的可以做一下。https://github.com/inorichi/tachiyomi-extensions/issues

**Comment by KoedaNagi** [comment]
其实可以学异次元漫画APP 里的加图源的方法
