### ISSUE TITLE
Dmzj v2源 解析错误

### ISSUE THREAD

**Issue by zhongfly** [feilongfl/Cimoc#21]
动漫之家漫画站临时关站整顿，但manhua.dmzj.com（pc版）访问正常，可以正常使用。
但在app中，来自该源的漫画均会显示“解析失败”，获取不了详情，无法阅读。
在8054版本中“图源”页面，点击动漫之家v2，点击搜索，可以正常查看本日的漫画更新列表。

**Comment by feilongfl** [comment]
关站整顿，好吧，估计整顿完也没剩什么了 :cry:

**Comment by zhongfly** [comment]
好吧，现在完全关了，昨晚漫画子站还打得开…这次主要是会清理隐藏漫画…本来cimoc就不能看隐藏漫画

fei long <notifications@github.com> 于 2018年12月6日周四 09:12写道：

**Comment by zhongfly** [comment]
又能看了……奇怪，虽然网页版自然是挂的，但cimoc又能看漫画了

**Comment by feilongfl** [comment]
动漫之家漫画更新没停过，部分漫画无法访问，但是新更新的貌似都可以
