### ISSUE TITLE
tachiyomi避难来了

### ISSUE THREAD

**Issue by Steve-337** [feilongfl/Cimoc#218]
之前用的是cimoc，后来发现tachiyomi动漫之家能搜索到隐藏漫画，但是现在凉了……**（现在已经可以搜索神隐漫画了，因为动漫之家搜索API恢复了神隐漫画搜索，只不过神隐漫画只能在晚上才能获得章节和漫画信息，白天会提示漫画不存在，已经加载的章节全天可看）**
还有tachiyomi那边的漫画堆插件好像也是fl做的吧，那边漫画堆有些漫画会这样
![Screenshot_2019-10-23-12-33-55-748](https://user-images.githubusercontent.com/48684035/67357940-75fba580-f591-11e9-89a1-eaf79fd5ff60.png)
而comic则正常

![Screenshot_2019-10-23-12-34-12-331](https://user-images.githubusercontent.com/48684035/67358009-a2172680-f591-11e9-9dc0-f8435c38db59.png)
我看了一下，应该是cimoc解析的是漫画堆手机版网页，而tachiyomi解析的是电脑版网页
（电脑版）
![Screenshot_2019-10-23-12-37-40-469](https://user-images.githubusercontent.com/48684035/67358142-0803ae00-f592-11e9-8562-68470e2ceb8a.png)
（手机版）
![Screenshot_2019-10-23-12-38-09-30](https://user-images.githubusercontent.com/48684035/67358167-1c47ab00-f592-11e9-865f-3e6cd3a5d759.png)
希望大佬能修复一下tachiyomi的插件

**Comment by in-out** [comment]
tachiyomi 我这边是一直retry

**Comment by Mortalit** [comment]
还有能搜到动漫之家隐藏的app吗

**Comment by Steve-337** [comment]
> 还有能搜到动漫之家隐藏的app吗

动漫之家搜索API又可以搜索神隐漫画了，所以tachiyomi现在可以搜索神隐漫画

**Comment by Mortalit** [comment]
为啥有些漫画能搜出来,但点进章节看不了解析出错

**Comment by Steve-337** [comment]
> 为啥有些漫画能搜出来,但点进章节看不了解析出错

动漫之家吗？要是的话现在动漫之家已经对神隐漫画进行了更彻底的锁定，根本获取不到漫画的章节信息，还是试试其他源吧！
