### ISSUE TITLE
[CS]還有在更新嗎

### ISSUE THREAD

**Issue by a1923386029** [feilongfl/Cimoc#231]
還有在更新嗎，每次啟動都顯示檢測到新版本。

**Comment by toesbieya** [comment]
用的github的api有问题，release都出到40了，但是api返回最新的还是39，作者应该是不会更新了

**Comment by KoedaNagi** [comment]
挺多bug没修复的。几个月了作者都没动静，

**Comment by KoedaNagi** [comment]
挺多问题没修复的。作者都没更新了

**Comment by feilongfl** [comment]
pre-release不算在release里面，所以会有提示。
