### ISSUE TITLE
请问老哥有意向做一个uwp的漫画平台吗？

### ISSUE THREAD

**Issue by SaltedFish-Extreme** [feilongfl/Cimoc#233]
就和uwp的动漫之家一样，方便在电脑上看

![BD6EDA536BDB66A731CC50EC10743BFA](https://user-images.githubusercontent.com/54784104/71819953-85868700-30c8-11ea-895a-afbb99a9630e.jpg)

**Comment by feilongfl** [comment]
暂时没有，已经入了android电子书的大坑。

（可以弄个android机顶盒，搞个手柄看漫画，以前觉得平板抱着太累做了蓝牙手柄的功能，我的是xbox 手柄）

**Comment by SaltedFish-Extreme** [comment]
好吧，谢谢老哥了_(:D)∠)_------------------ 原始邮件 ------------------
发件人: "fei long"<notifications@github.com>
发送时间: 2020年2月4日(星期二) 上午10:38
收件人: "feilongfl/Cimoc"<Cimoc@noreply.github.com>;
抄送: "咸鱼至尊"<1738099872@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [feilongfl/Cimoc] 请问老哥有意向做一个uwp的漫画平台吗？ (#233)



暂时没有，已经入了android电子书的大坑。
 
（可以弄个android机顶盒，搞个手柄看&#x6F2B;画）
 
&mdash;
