### ISSUE TITLE
为什么打开设置就闪退，怎么从左到右浏览啊？

### ISSUE THREAD

**Issue by hentaishopkeeper** [feilongfl/Cimoc#242]

**Comment by feilongfl** [comment]
版本？

**Comment by feilongfl** [comment]
还有设备信息？

**Comment by hentaishopkeeper** [comment]
> 还有设备信息？

软件版本 version: v1.5.0-beta2(484)，设备信息 xiaomi mix2s, Android 10, MIUI 20.1.21

**Comment by feilongfl** [comment]
突然想起来设置闪退好象是因为没有存储权限来着吧

**Comment by hentaishopkeeper** [comment]
> 突然想起来设置闪退好象是因为没有存储权限来着吧

俺一直都给了，没有用

**Comment by zsp754642483** [comment]
我的也是闪退,噗呲
软件版本 version: v1.5.0-beta2(484)，设备信息 xiaomi MI9, Android 10, MIUI 11.0.5.0

**Comment by zsp754642483** [comment]
点击设置闪退

**Comment by feilongfl** [comment]
貌似升级环境造成了1.5系列release在部分机型闪退，但我手边暂时没有能测试的机器，争取这个月修下。

1.5与1.4的漫画源是相同的。

**Comment by feilongfl** [comment]
今天搜了一下，安卓Q的存储变化很大，需要点时间进行适配。

目前采取下面临时方法解决。
```
android:requestLegacyExternalStorage="true"
```

测试版本`v1.5.0-beta3`

闪退问题集中：
#255
