### ISSUE TITLE
备份好像出了问题

### ISSUE THREAD

**Issue by KawasakiZ900** [feilongfl/Cimoc#245]
我是1. 5. 5beta1我恢复的时候说找不到备份文件，但我自己翻文件的时候翻到了自己的备份数据。

**Comment by feilongfl** [comment]
貌似升级环境造成了1.5系列release在部分机型闪退，但我手边暂时没有能测试的机器，争取这个月修下。

1.5与1.4的漫画源是相同的。

**Comment by pzy2222** [comment]
> 貌似升级环境造成了1.5系列release在部分机型闪退，但我手边暂时没有能测试的机器，争取这个月修下。
> 
> 1.5与1.4的漫画源是相同的。

安卓10机器好像无法读取写入储存，1.4.47、1.4.49和1.5都是这样

**Comment by feilongfl** [comment]
恩，看起来是这样，设置闪退应该也是存储的问题

**Comment by feilongfl** [comment]
今天搜了一下，安卓Q的存储变化很大，需要点时间进行适配。

目前采取下面临时方法解决。
```
android:requestLegacyExternalStorage="true"
```

测试版本`v1.5.0-beta3`

闪退问题集中：
#255
