### ISSUE TITLE
Parser能否动态更新？

### ISSUE THREAD

**Issue by toesbieya** [feilongfl/Cimoc#257]
因为改动频率最大的就是Parser，而且改也基本上是小改。
另外这样的话可以动态选择Parser源，比如可以选你官方的实现，自己不满意可以改成自己的实现。

技术上的话，java可以动态加载class文件，把所有Parser当本地文件放一起，应用启动时再去加载，然后加个按钮一点就去github仓库里找需要更新的Parser，顺便写入本地文件。

这样是否可行？

**Comment by feilongfl** [comment]
当然可行，`tachiyomi`那边就是这样。
