### ISSUE TITLE
竖屏问题bug

### ISSUE THREAD

**Issue by akbcd6846268** [feilongfl/Cimoc#258]
手机打横放，会出现横屏，并且手机已经锁定竖屏了，还是这样，手机是iqooPro安卓Q

**Comment by feilongfl** [comment]
哪个界面？

如果不是阅读界面的话，确实被我设置成了跟随传感器。因为我发现在安卓电视上界面不正常。

**Comment by LenKiMo** [comment]
作品列表界面，作品章节界面，即使手机关闭了屏幕旋转开关，也会自动旋转。
建议在设置中对这部分界面也增加屏幕旋转开关，以允许用户锁定为竖屏显示。

**Comment by 362516282** [comment]
请取消无视系统竖屏锁定的旋转

**Comment by akbcd6846268** [comment]
建议加个开关，毕竟有时候躺着用手机，非阅读界面确实会无视系统锁定旋转

**Comment by feilongfl** [comment]
已经改成跟随系统了，下个版本一起发布

**Comment by feilongfl** [comment]
先把这个功能发布了
