### ISSUE TITLE
[CS] 动漫之家

### ISSUE THREAD

**Issue by mokurin000** [feilongfl/Cimoc#259]
# 这是一个漫画源问题

## 出现错误的漫画源
动漫之家v2 解析错误

## 您搜索/观看的漫画名称或关键字以及访问链接
[别当欧尼酱了！](https://manhua.dmzj.com/biedangounijiangle/) 动漫之家
## 在以下环节中出现错误
- [ ] 搜索
- [x] 章节信息
- [ ] 图片加载

## 你是否使用科学上网工具
- [x] 是
- [ ] 否

## 你是否能够访问漫画源网页并成功加载漫画图片
- [x] 是
- [ ] 否

## 您手机的系统版本
- [x] 原生(AOSP/LL/RR/Mokee等)
- [ ] 国产(小米/氢氧/锤子)
具体版本: 

## 您使用的cimoc版本
V1.5.0

**Comment by feilongfl** [comment]
![image](https://user-images.githubusercontent.com/10269596/77246452-5a8ce780-6c62-11ea-9996-648738ac0612.png)

没发现问题。。。

**Comment by Steve-337** [comment]
动漫之家今天网站炸了一会，已经恢复了
