### ISSUE TITLE
请教一下漫画切换阅读模式，在代码里是在什么地方恢复之前的阅读位置的？望大佬解惑~

### ISSUE THREAD

**Issue by YumikoAzu** [feilongfl/Cimoc#260]

**Comment by feilongfl** [comment]
在
app\src\main\java\com\hiroshi\cimoc\ui\activity\ReaderActivity.java:391

``` java
    @Override
    public void onInitLoadSuccess(List<ImageUrl> list, int progress, int source, boolean local) {
        setReaderAdapter(list, source, local);
        mReaderAdapter.addAll(list);
        if (progress != 1) {
            mRecyclerView.scrollToPosition(progress - 1);
        }
        mLoadingText.setVisibility(View.GONE);
        mRecyclerView.setVisibility(View.VISIBLE);
        updateProgress();
    }
```

**Comment by YumikoAzu** [comment]
> 在
> app\src\main\java\com\hiroshi\cimoc\ui\activity\ReaderActivity.java:391
> 
> ```java
>     @Override
>     public void onInitLoadSuccess(List<ImageUrl> list, int progress, int source, boolean local) {
>         setReaderAdapter(list, source, local);
>         mReaderAdapter.addAll(list);
>         if (progress != 1) {
>             mRecyclerView.scrollToPosition(progress - 1);
>         }
>         mLoadingText.setVisibility(View.GONE);
>         mRecyclerView.setVisibility(View.VISIBLE);
>         updateProgress();
>     }
> ```

多谢解答~
