### ISSUE TITLE
在逍遥模拟器上搜索漫画后立刻闪退

### ISSUE THREAD

**Issue by Gokou-Ruri** [feilongfl/Cimoc#267]
输入关键词，点击搜索后，出现搜索结果，但APP随后立刻闪退，此问题可以百分百复现。
模拟器的Android版本如下：
![image](https://user-images.githubusercontent.com/26711804/79295358-114f5100-7f0b-11ea-9f1b-238ef063d786.png)
未添加额外的源，APP版本为最新的1.5.1版，但打开APP后会弹出toast显示“检测到新版本”。
![image](https://user-images.githubusercontent.com/26711804/79295586-99cdf180-7f0b-11ea-9cd5-93b3ae5f5e04.png)
![image](https://user-images.githubusercontent.com/26711804/79295596-a0f4ff80-7f0b-11ea-8615-a836fe6d58b7.png)

**Comment by Gokou-Ruri** [comment]
https://ws28.cn/f/2ajeab3tg2w 闪退录屏

**Comment by Gokou-Ruri** [comment]
我发现只要在手机上安装并启动Cimoc，之后搜索漫画，然后退出Cimoc，用Swift Backup备份Cimoc（含数据），放到逍遥模拟器上恢复备份，之后就能正常阅读和搜索漫画。
但还是不清楚为什么直接在逍遥模拟器上安装Cimoc后无法搜索漫画。

**Comment by zhenchao** [comment]
这个问题似乎是没有授予存储空间权限导致的
