### ISSUE TITLE
[图源]考虑添加bilibili漫画，以及图源登录帐号功能

### ISSUE THREAD

**Issue by zhongfly** [feilongfl/Cimoc#27]
哔哩哔哩已经收购网易漫画，可以预见，今后B站漫画也将是一个大平台，故要求考虑添加哔哩哔哩漫画(目前只有app版，无网页)
另外由于一些网站可能需要登录才能够查看，请求考虑添加登录帐号功能

**Comment by feilongfl** [comment]
emmm，b站的话用官方客户端好像免流 :smile: 抓包好麻烦，不知为什么b站漫画不做网页

登录才能看的一般是收费漫画吧，一般别的源里有 :smiley:

**Comment by feilongfl** [comment]
今天看了看b站，发现是有网页版的

> http://manga.bilibili.com/m

**Comment by feilongfl** [comment]
emmm,b站漫画和其他漫画源相比没什么优势啊,先不添加

**Comment by History-exe** [comment]
B站漫画还是不要添加比较好。小心惹火上身。

**Comment by feilongfl** [comment]
@History-exe 2333,好像有人收律师函来着，b站不让第三方来着:disappointed_relieved:
