### ISSUE TITLE
检查漫画更新时，标记解析失效的漫画

### ISSUE THREAD

**Issue by zhongfly** [feilongfl/Cimoc#29]
由于众说周知的原因，某些漫画会在一些漫画源消失，为更方便的发现，能否将解析失败(检查更新失败)的漫画标记出来？比如名字前加一个红色的叹号？或是其他方式
希望能给予考虑

**Comment by feilongfl** [comment]
最近在考虑用flutter重写整个程序，所以这个不打算继续增加新功能了。
