### ISSUE TITLE
漫画堆的链接错误

### ISSUE THREAD

**Issue by popopjk** [feilongfl/Cimoc#292]
能搜得到漫画但是不能阅读，漫画堆的网址从manhuadui变成漫画bei了。

还有就是打开软件之后会一直弹出检测到更新

**Comment by huangguabaizhan** [comment]
作者应该不会再更新了

**Comment by ghost** [comment]
> 作者应该不会再更新了

已经由其他开发者接手了，新分支https://github.com/Haleydu/Cimoc/releases
