### ISSUE TITLE
关于app不能下载的问题

### ISSUE THREAD

**Issue by eggsoops** [feilongfl/Cimoc#295]
更新的最近几个版本app，不知道为什么下到一半都不能正常的下载，导致一直没法更新，也不是本人的网络问题，希望得到解答。

**Comment by feilongfl** [comment]
应该是网络的问题


单独发一下v1.5.3
过期时间 2020-08-02

https://c-t.work/s/3e619680a0fe40

**Comment by eggsoops** [comment]
> 应该是网络的问题
> 
> 单独发一下v1.5.3
> 过期时间 2020-08-02
> 
> https://c-t.work/s/3e619680a0fe40

这回可以成功的下载了，感谢，不过没明白到底是什么原因
