### ISSUE TITLE
[CS]动漫之家漫画源错误及原因分析

### ISSUE THREAD

**Issue by zhongfly** [feilongfl/Cimoc#298]
# 这是一个漫画源问题

> 漫画源工作情况可以在[project](https://github.com/feilongfl/Cimoc/projects/2)中进行查看，请尽量不要重复
> 请您在提交本问题前仔细完成下面问题以便更好地解决问题.
> 如果有多个漫画源出错，请不要合并在一起，谢谢

## 出现错误的漫画源
动漫之家v2
## 您搜索/观看的漫画名称或关键字以及访问链接
所有该漫画源的漫画
例：恋物循环
https://m.dmzj.com/info/lianwuxunhuan.html

## 在以下环节中出现错误
- [x] 搜索
- [x] 章节信息
- [x] 图片加载

## 你是否使用科学上网工具
- [ ] 是
- [x] 否

## 你是否能够访问漫画源网页并成功加载漫画图片
- [x] 是
- [ ] 否

## 您手机的系统版本
- [x] 原生(AOSP/LL/RR/Mokee等)
- [ ] 国产(小米/氢氧/锤子)
具体版本: 

## 您使用的cimoc版本
version: v1.5.3 (513)

具体问题及分析：
以恋物循环为例
cimoc中使用 https://m.dmzj.com/info/lianwuxunhuan.html 访问，但该网址无效(使用浏览器访问该网页同样会失败)，返回错误Internal Server Error，并且使用http访问会有302错误
如果浏览器使用 https://m.dmzj.com/info/lianwuxunhuan 末尾无.html的链接，可以正常访问。

猜测原因是dmzj拒绝了末尾有.html的网址访问，但cimoc却只会使用末尾带有.html的网址。
在cimoc中，通过搜索无动漫之家源的结果；浏览器访问https://m.dmzj.com/info/lianwuxunhuan 后，通过分享到cimoc的添加漫画，cimoc无响应

**Comment by zhongfly** [comment]
@Haleydu 希望其他分支的作者也关注一下这个问题

**Comment by Haleydu** [comment]
好的

**Comment by zhongfly** [comment]
另外：搜索无结果的问题：
动漫之家源(非v2版)：
cimoc访问的搜索接口正常返回了数据，但是结果中的中文为unicode(例如comic_name":"\u604b\u7269\u5faa\u73af")，可能是cimoc目前并不会对此解码导致搜索结果为空
v2版：
直接返回了一个网页，我无法得知cimoc是否能正确提取出结果

**Comment by Nathaniel-Wu** [comment]
有一样的问题

**Comment by Nathaniel-Wu** [comment]
好像部分漫画的解析突然又恢复正常了…

**Comment by feilongfl** [comment]
刚刚测试这个漫画没发现问题

![photo_2020-10-11_13-30-27](https://user-images.githubusercontent.com/10269596/95671149-fd3c9180-0bc5-11eb-89af-c5bd09e64851.jpg)
