### ISSUE TITLE
feature request: 开始所有已暂停下载

### ISSUE THREAD

**Issue by trim21** [feilongfl/Cimoc#3]
现在的下载在应用退出之后会全部暂停- -

**Comment by feilongfl** [comment]
上周有点事情，没顾上这边

退出之后暂停请检查是不是有后台管理软件，顺便开始按钮在下载页面右下角

![photo_2018-04-16_22-39-20](https://user-images.githubusercontent.com/10269596/38815688-2123959c-41c7-11e8-976a-15aa17fd4c84.jpg)

**Comment by trim21** [comment]
啊...我指的是控制只开始某一部漫画的下载
不是认为应用退出之后下载暂停有什么问题,只是想描述一下使用场景...

**Comment by feilongfl** [comment]
add this feature in v1.4.8.8044.
