### ISSUE TITLE
看漫画源失效

### ISSUE THREAD

**Issue by zhongfly** [feilongfl/Cimoc#32]
## 以下均出现问题
https://tw.manhuagui.com/comic/28723
https://tw.manhuagui.com/comic/29239
https://tw.manhuagui.com/comic/15279
等所有该源漫画

## 在以下环节中出现错误
图片加载(并非直接提示无法加载，而是加载1s便失败，显示↻，反复多次×)
章节信息加载正常，搜索正常

## 你是否使用科学上网工具
是(全局代理+关闭分应用代理 仍然无法加载)

## 你是否能够访问漫画源网页并成功加载漫画图片
是，可以正常浏览，并且不存在加载迟缓的情况，加载速度正常

## 您手机的系统版本
RR
具体版本: Android 7.1

## 您使用的cimoc版本
version: v1.4.8.8058-2(59)

**Comment by feilongfl** [comment]
已修复，跟随下一版本发布。
