### ISSUE TITLE
扑飞漫画**部分**无法下载

### ISSUE THREAD

**Issue by amypot** [feilongfl/Cimoc#320]
[扑飞漫画源](http://m.pufei.cc)**部分**无法下载的问题

**部分**图片下载链是
http://res.img.youzipi.net/images/2021/06/04/00/332bd568ac.jpg/0

部分是
http://res.img.youzipi.net/images/2021/05/30/21/47c8ebfb6b.jpg

有什么好方法嘛

**Comment by feilongfl** [comment]
由于精力有限,这个很久没有维护了,Android的tachiyomi处于积极维护的状态,可以尝试.
