### ISSUE TITLE
翻页效果问题

### ISSUE THREAD

**Issue by saasddsaasdd** [feilongfl/Cimoc#33]
首先感谢大佬，现在这个版本已经很好啦。但是目前的版本里，勾选上快速翻页之后，实际阅读的时候还是有平移的动画效果，大佬能否去掉这个动画效果？我使用最后一版的原版cimoc是没有这个翻页动画效果的，谢谢大佬

**Comment by feilongfl** [comment]
没用过这个功能，我手机屏幕比较小，一般横屏看的 :smile: 
之后我看下程序吧，要是原版有的话没准是被我不小心删了 :smile:

**Comment by wyxrxy** [comment]
原版是有的

**Comment by feilongfl** [comment]
测试版本:
[v1.4.8.8061-3](https://github.com/feilongfl/Cimoc/releases/tag/v1.4.8.8061-4)

**Comment by feilongfl** [comment]
我在手机上测试最新版本没有问题，如果还有问题的话请直接回复
