### ISSUE TITLE
下载问题

### ISSUE THREAD

**Issue by TheCardistry** [feilongfl/Cimoc#34]
扑飞动漫的源可以看，但无法下载，最新版，安卓6.0

**Comment by feilongfl** [comment]
扑飞好像有访问频率限制，你可以尝试下我的另一个项目feilongfl/c-get
不过c-get是我用来学习go的，所以不是很稳定:smile:

**Comment by 3839126** [comment]
> 扑飞好像有访问频率限制，你可以尝试下我的另一个项目feilongfl/c-get
> 不过c-get是我用来学习go的，所以不是很稳定😄
好的多谢(o^^o)

**Comment by TheCardistry** [comment]
> 扑飞好像有访问频率限制，你可以尝试下我的另一个项目feilongfl/c-get
> 不过c-get是我用来学习go的，所以不是很稳定😄

多谢

**Comment by TheCardistry** [comment]
> 扑飞好像有访问频率限制，你可以尝试下我的另一个项目feilongfl/c-get
> 不过c-get是我用来学习go的，所以不是很稳定😄

老哥，你的c-get咋用啊，一直提示
`FATA[0000] no parse match`
help看不懂😂

**Comment by feilongfl** [comment]
emmm,看了下要是扑飞漫画的话之前忘了把手机版网址加进去了😄
![](https://lh3.googleusercontent.com/-hvCuw6ooNBE/XDrjgD6nIJI/AAAAAAAAQ2U/Rurw-NxQGhA87TplS6Kl8RJPhuApp0EAgCHMYCw/s0/powershell_2019-01-13_15-06-35.png)

~~你可以试试https://github.com/feilongfl/c-get/releases/tag/v0.1.5~~
刚才没睡醒😄迷迷糊糊提交了个bug上去😄,现在醒了,你把m.pufei改成www.pufei就好了

**Comment by wufakanqingweilai** [comment]
看漫画源，下载了一会儿，然后在线看都看不了，😅挂上小飞机后也这样。看来有限制。

**Comment by feilongfl** [comment]
> 看漫画源，下载了一会儿，然后在线看都看不了，挂上小飞机后也这样。看来有限制。

嗯嗯，有些漫画源有请求速度限制的
