### ISSUE TITLE
57漫画源失效

### ISSUE THREAD

**Issue by wai15985** [feilongfl/Cimoc#38]
因为57漫画的网址有改变吗

**Comment by feilongfl** [comment]
这个漫画源章节不全:angry:有点不想更新:stuck_out_tongue_winking_eye:

**Comment by feilongfl** [comment]
试了一下,没发现失效的漫画啊😕

**Comment by wai15985** [comment]
我的收藏都进不去😭
连搜寻结果也不出现了
网页版57mh.com也换成5qmh.com才能上

**Comment by feilongfl** [comment]
@wai15985 emmm，看来换域名了

**Comment by feilongfl** [comment]
已修正,跟随下一版本更新
