### ISSUE TITLE
Webtoon 失效了

### ISSUE THREAD

**Issue by ybhgl** [feilongfl/Cimoc#39]
在国内访问Webtoon会自动跳转到咚漫（www.dongmanmanhua.com），但是软件不支持解析咚漫（其实网页和Webtoon很像，有些许不同）

**Comment by feilongfl** [comment]
这个失效的比较彻底？搜索里面没看见:cold_sweat:

**Comment by ybhgl** [comment]
> 这个失效的比较彻底？搜索里面没看见

对啊，能修复吗？

**Comment by feilongfl** [comment]
@ybhgl 修正至台湾版本，跟随下一版本发布
