### ISSUE TITLE
bug： 自动切割大图之后的结果跟原本的顺序相反

### ISSUE THREAD

**Issue by trim21** [feilongfl/Cimoc#4]
原本是[1 2]的大图被切割之后的显示顺序是[2]，[1]

**Comment by feilongfl** [comment]
额，默默的表示没用过这个功能😅

**Comment by trim21** [comment]
...won't fix了吗

**Comment by feilongfl** [comment]
一直没找到大图:joy:

**Comment by trim21** [comment]
噗 按错了
https://m.dmzj.com/info/2219.html
这个链接里的图都是大图，看着要累死人了233
准备学一下Java自己修一下了…

**Comment by trim21** [comment]
好多分支啊，有什么workflow吗，提交PR的话提交到哪个分支…

**Comment by trim21** [comment]
哦，看到你在其他issue的回复了…
所以flutter版本的仓库建了吗，我先watch一下😂

**Comment by trim21** [comment]
https://github.com/Arachnid-27/Cimoc/blob/7369678e4481b8e08c25c62f9b11b694ebb4016c/app/src/main/java/com/hiroshi/cimoc/ui/activity/ReaderActivity.java#L305

问题好像出在这里，先暂记一下（

**Comment by feilongfl** [comment]
feilongfl/avis
刚开了个头，准备向kodi学习，使用python插件，就是不知道能不能弄出来:joy:

**Comment by feilongfl** [comment]
我这边发布的分支是release-tci

**Comment by feilongfl** [comment]
等了一周PR,貌似 @Trim21 没什么进展,我自己实现了.顺便兄弟你没找对地方😏

切割大图的方法在:
https://github.com/feilongfl/Cimoc/blob/v1.4.8.8071/app/src/main/java/com/hiroshi/cimoc/fresco/processor/MangaPostprocessor.java#L61

具体实现很简单了,换换坐标就好了,你可以参考提交
https://github.com/feilongfl/Cimoc/commit/44cbe9f176f3d26c09dd74a514fa9ae3b7074825

跟随下一版本更新.

**Comment by trim21** [comment]
最近年底事比较多，一直没腾出时间…

没太看懂你修改的这个做法…感觉直接翻转切割后大图的顺序比较好，为什么选择了加一个默认不启用的配置项…正常漫画不都是先左后右吗。

**Comment by ckn4** [comment]
貌似台版漫画是先右后左的？这样的话大图切出来又反了，这样留一个选项挺好的

**Comment by trim21** [comment]
@ckn4 原来如此…

**Comment by feilongfl** [comment]
额,我的印象里漫画不都是从右往左的么,至少google play上买的漫画和小说都是从右往左翻.看到你发这本链接我感觉很奇特😂

**Comment by feilongfl** [comment]
不过我没买过实体书,要是有实体书大佬科普一下就好了

**Comment by trim21** [comment]
@feilongfl 日漫偶尔出现的大图都是先左后右, 在app里顺序颠倒的😂
(一时间除了上面那本书我也找不到其他合适的例子了)
