### ISSUE TITLE
[图源请求]推荐一个更新快且全的图源

### ISSUE THREAD

**Issue by ckn4** [feilongfl/Cimoc#40]
这个网站漫画真的更新的快也比较全
http://www.2animx.com/
自己前两天试着添加，还是遇到了点小麻烦。水平远远不够，希望大佬考虑能不能添加这个图源。

**Comment by ckn4** [comment]
遇到的问题是：这个图源有些长的列表展开和有些漫画章节的加载需要js。之前添加另外一个图源的时候，那个网站图片是懒加载的，抓到的网页根本就没有图片，这些问题我还解决不了。

**Comment by feilongfl** [comment]
简单看了一下，应该是只能按照lazy的方法来添加，印象里面有别的源是类似的，我把它先添加进[crss](https://cimoc.netlify.com)的爬虫里面，看看更新频率

ps: 最近感冒实在不想看代码,已经鸽了一个漫画源了：（
（打开动漫狂的代码一看，整整齐齐的表格布局，没class也没id，表示好多年不见这样的了）

**Comment by feilongfl** [comment]
已添加,跟随下一版本发布
