### ISSUE TITLE
搜索能不能通过id搜索？

### ISSUE THREAD

**Issue by wufakanqingweilai** [feilongfl/Cimoc#41]
动漫之家好多神隐的漫画，通过漫画id搜索可好？

**Comment by feilongfl** [comment]
@wufakanqingweilai 请举个🌰

**Comment by feilongfl** [comment]
话说不是关站了么，难道有技巧？

**Comment by wufakanqingweilai** [comment]
只是首页打不开，进入二级页面，比如最近更新https://m.dmzj.com/latest.html  https://manhua.dmzj.com/update_1.shtml就行。动漫之家uwp版提供有通过id搜索挺方便的。

**Comment by wufakanqingweilai** [comment]
@feilongfl

**Comment by feilongfl** [comment]
你是这个意思么?

![](https://i.ooxx.ooo/2019/01/31/40bcc67cb4c430c703e3f1b964ea0dec.webp)

**Comment by feilongfl** [comment]
@wufakanqingweilai 

额,剪辑时候多剪了一秒😄,最后就是cimoc打开了~~

**Comment by wufakanqingweilai** [comment]
其实我的意思是直接在动漫之家源，搜索框搜索ID。好吧，这个貌似更合理，不用扒网页源码找ID了。@feilongfl

**Comment by wufakanqingweilai** [comment]
### win10平台上UWP的动漫之家是这样搜索神隐漫画的。挺方便，就是需要知道ID。@feilongfl
![20190131135718](https://user-images.githubusercontent.com/19898128/52033745-fa6c4b00-2560-11e9-82b0-9f58ce80e6d6.png)
![20190131135754](https://user-images.githubusercontent.com/19898128/52033747-fc360e80-2560-11e9-9300-a17088c19e6b.png)
