### ISSUE TITLE
为什么海贼王和巨人搜不出来？

### ISSUE THREAD

**Issue by github-24** [feilongfl/Cimoc#42]
原cimoc可以

**Comment by feilongfl** [comment]
![photo_2019-02-01_16-57-11](https://user-images.githubusercontent.com/10269596/52112930-f1ec4100-2642-11e9-9e63-1925dcae69c3.jpg)
![photo_2019-02-01_16-57-14](https://user-images.githubusercontent.com/10269596/52112931-f284d780-2642-11e9-91cc-05b63c88e108.jpg)

请检查网络情况，或附加更多信息

**Comment by github-24** [comment]
海賊王那个解析不了，原cimoc海贼和巨人两个是动漫之家的源，在你这个版本现在搜不出来

**Comment by feilongfl** [comment]
> 海賊王那个解析不了，原cimoc海贼和巨人两个是动漫之家的源，在你这个版本现在搜不出来

能看的,虽然我很懒,但还不至于懒到搜索一下就截图回复😂两个漫画我都看了
有些站点不能解析请检查是否能打开相关网页,如果不能请检查网络环境

动漫之家关站中,暂不修复

**Comment by feilongfl** [comment]
动漫之家你可以参考 https://github.com/feilongfl/Cimoc/issues/41

**Comment by github-24** [comment]
> 动漫之家你可以参考 #41

不是网络的问题，刚才试了一下还是解析错误。还有很奇怪的一件事，动漫之家找不到海贼和巨人了，但是原cimoc之前收藏的还会更新，也还能搜的出来

**Comment by feilongfl** [comment]
动漫之家相关问题暂不处理，其他漫画源问题为了快速解决请按照[模板](https://github.com/feilongfl/Cimoc/issues/new?assignees=&labels=%E6%BC%AB%E7%94%BB%E6%BA%90%E9%97%AE%E9%A2%98&template=comic-source-issues.md&title=%5BCS%5D)填写
