### ISSUE TITLE
[CS]2animx源加载问题

### ISSUE THREAD

**Issue by ckn4** [feilongfl/Cimoc#43]
# 这是一个漫画源问题

> 请您在提交本问题前仔细完成下面问题以便更好地解决问题.
> 如果有多个漫画源出错，请不要合并在一起，谢谢

## 出包女王
http://www.2animx.com/index-comic-name-%E5%87%BA%E5%8C%85%E5%A5%B3%E7%8E%8B-id-13333

## 在以下环节中出现错误
- [ ] 图片加载

## 你是否使用科学上网工具
- [ ] 是

## 你是否能够访问漫画源网页并成功加载漫画图片
- [ ] 是

## 您手机的系统版本
- [ ] 国产(emui)
具体版本: 8.0

搜索这类限制级漫画时，需要点击页面上按钮才能加载章节，求问有没有办法解决？

**Comment by feilongfl** [comment]
emmm,限制级...好吧有个cookies,我看看怎么加上

**Comment by feilongfl** [comment]
加上了,等编译吧,大概十分钟

**Comment by feilongfl** [comment]
emmm,由于我在写别的东西,所以修补丁时候没测试好,这回好了

https://github.com/feilongfl/Cimoc/releases/tag/v1.4.8.8063-2
