### ISSUE TITLE
看漫画时如果能有一个正序倒序功能就好了

### ISSUE THREAD

**Issue by murongmingrui** [feilongfl/Cimoc#44]
看漫画时如果想从第一话开始看都得往下划好久，太费劲了，如果能添加一个正序倒序功能就好了~

**Comment by feilongfl** [comment]
@murongmingrui  你可以直接点那个表

**Comment by feilongfl** [comment]
就是♥上面那个

**Comment by murongmingrui** [comment]
> 就是♥上面那个

这个按键我试过。但这个是从第一话开始看，但如果我想看第30话，那也得一话话的翻啊，不如加一个正序倒序来的方便~

**Comment by feilongfl** [comment]
已添加,跟随下一版本更新
