### ISSUE TITLE
功能建议

### ISSUE THREAD

**Issue by History-exe** [feilongfl/Cimoc#45]
希望增加重力旋屏功能。

**Comment by feilongfl** [comment]
added 

https://github.com/feilongfl/Cimoc/releases/tag/v1.4.14

**Comment by History-exe** [comment]
重力旋屏功能有问题。我在阅读配置的屏幕方向里发现了个“自动”的选项，请问那个就是吗？我设置之后，进入漫画，并没有重力旋屏。
另外作者幸苦了。

**Comment by feilongfl** [comment]
@History-exe  需要系统开启自动旋转才能生效

**Comment by History-exe** [comment]
@feilongfl 好的。明白了。

**Comment by boxjohn** [comment]
建议加入自动查找更新最快源，还有漫画目录加入贴吧跳转，希望完结并且看完的漫画有专门的地方放着，和正在追的区分开，希望正在开发的云同步国内使用坚果云www.jianguoyun.com，国内使用更友好，最后谢谢开发者大大的无私奉献，这个app好用极了
