### ISSUE TITLE
app似乎会导致被看漫画源封IP

### ISSUE THREAD

**Issue by sacrish** [feilongfl/Cimoc#46]
症状：每次用一个新IP（裸IP或梯子）可以浏览看漫画源，过一两天就解析错误。重新拨号或者换梯子一般可以恢复正常，但一段时间后又会解析错误。

看起来是看漫画会定期封掉某些浏览过的IP，不知道是否跟app有关系。

**Comment by History-exe** [comment]
看漫画在我印象里是大陆访问不了的，据原作者说是看漫画屏蔽了大陆IP。

**Comment by sacrish** [comment]
几个月前裸连不行，后来用电信和移动都试过可以看了。挂梯子是一开始可以看，但每个ip只能看一两天，之后就解析错误，需要换梯子。

**Comment by feilongfl** [comment]
emmm，貌似是短时间内加载过多图片会被封ip，也就是说看的太快了:joy: 
这个问题属于漫画源限制，修改图片加载延时可能会解决，但是由于不知道具体的限制如何，所以我可能要测试一段时间

**Comment by kanasimi** [comment]
~~chapter_time_interval : '40s' seems OK~~
https://github.com/kanasimi/work_crawler/blob/b23ee46e50075c664a4a87ffdcd9b6c974d3c6e1/comic.cmn-Hans-CN/manhuagui.js#L62

更正: 40秒還是會被ban
3 min seems OK

**Comment by feilongfl** [comment]
3min指的是章节加载的间隔时间？但是正常看漫画等三分钟人会疯的吧😀

**Comment by kanasimi** [comment]
現在看來就算用4分鐘
還是會不定時被封鎖的樣子

**Comment by feilongfl** [comment]
@kanasimi 真想知道这个网站直接用网页看会不会封IP:joy_cat:

**Comment by kanasimi** [comment]
那簡單
自己試找人試都可以...就隨便拿部漫畫來看就是
