### ISSUE TITLE
加漫画源

### ISSUE THREAD

**Issue by wai15985** [feilongfl/Cimoc#47]
可以把咪咕漫画一起加上去吗
http://www.migudm.cn

**Comment by feilongfl** [comment]
最近正在与f-droid沟通修改分发问题，所以漫画源的问题会推迟一段时间

**Comment by feilongfl** [comment]
这个漫画源搜索的文字编码很有意思,一眼认不出来,但试了试搞出来了😀
尝试一个字
```
天 => JUU1JUE0JUE5
```

然后
```
天 ===utf-8===> \xE5\xA4\xA9 ===\x->%=====> %E5%A1%A9 ===base64=====> JUU1JUE0JUE5
```

**Comment by feilongfl** [comment]
https://github.com/feilongfl/Cimoc/releases/tag/v1.4.10

已添加
