### ISSUE TITLE
希望增加批量刪除本地漫畫功能

### ISSUE THREAD

**Issue by LeslieLee0420** [feilongfl/Cimoc#48]
Rt

**Comment by feilongfl** [comment]
额,用途感觉不大啊,于是说老哥你下了多少😂

**Comment by LeslieLee0420** [comment]
😂😂琉璃神社下的合集解壓出來就全載入了，一個一個刪除的工作量有點大。其實批量刪除這功能沒有也無傷大雅，反正用文件管理器也就一下子全刪除了

在 2019年2月10日週日 20:26，fei long <notifications@github.com<mailto:notifications@github.com>> 寫道：

额,用途感觉不大啊,于是说老哥你下了多少😂

**Comment by TheCardistry** [comment]
可以在数据库里实现批量删除

**Comment by feilongfl** [comment]
嗯，是可以从数据库直接删，但是这个功能貌似用的不多
