### ISSUE TITLE
请问可以添加zip rar 等格式的漫画吗？

### ISSUE THREAD

**Issue by horizonl** [feilongfl/Cimoc#49]
如题

**Comment by feilongfl** [comment]
没试过呢，我很少看本地，也没动过本地的代码

**Comment by horizonl** [comment]
@feilongfl 感谢回复，我也就是下了两部zip的，想试试，后来发现都是双页的不适合手机看:relaxed:

**Comment by feilongfl** [comment]
@horizonl 设置里面可以设置拆分

**Comment by History-exe** [comment]
想起了布卡漫画

**Comment by feilongfl** [comment]
@History-exe 挂了么？

**Comment by History-exe** [comment]
@feilongfl 没挂。只是想起布卡漫画有这个功能，查看本地的压缩包格式漫画。非常快速而且还能看那种带有压缩密码的。

**Comment by feilongfl** [comment]
> @feilongfl 没挂。只是想起布卡漫画有这个功能，查看本地的压缩包格式漫画。非常快速而且还能看那种带有压缩密码的。

原来如此，类似功能电脑用过，感觉手机上意义不大
