### ISSUE TITLE
[CS]

### ISSUE THREAD

**Issue by yanareat** [feilongfl/Cimoc#52]
# 这是一个漫画源问题

> 请您在提交本问题前仔细完成下面问题以便更好地解决问题.
> 如果有多个漫画源出错，请不要合并在一起，谢谢

## 出现错误的漫画源
http://m.5qmh.com/10716
## 您搜索/观看的漫画名称或关键字以及访问链接
四海奇龙……等等
## 在以下环节中出现错误
- [x] 搜索
- [ ] 章节信息
- [ ] 图片加载

## 你是否使用科学上网工具
- [ ] 是
- [x] 否

## 你是否能够访问漫画源网页并成功加载漫画图片
- [ ] 是
- [x] 否

## 您手机的系统版本
- [ ] 原生(AOSP/LL/RR/Mokee等)
- [x] 国产(小米/氢氧/锤子)
具体版本: miui9

## 您使用的cimoc版本
V1.4.10

**Comment by yanareat** [comment]
我发现分享以后的网址不对，可能网址变动了

**Comment by feilongfl** [comment]
@yanareat 感谢反馈，漫画网站移动至http://m.wuqimh.com
，下一版本修复

**Comment by yanareat** [comment]
那个看漫画的封ip的问题能解决吗？

**Comment by feilongfl** [comment]
@yanareat 这个暂时不能，可以多换换IP

**Comment by feilongfl** [comment]
fixed via https://github.com/feilongfl/Cimoc/releases/tag/v1.4.11
