### ISSUE TITLE
〔功能建议〕在收藏的封面上增加阅读记录的显示

### ISSUE THREAD

**Issue by oiwl** [feilongfl/Cimoc#54]
目前收藏上面只显示漫画的名称和来源，一旦源失效或者被下架的话，就不清楚上次读到哪了，尤其是有些更新很慢的漫画。
建议同时在上面显示目前记录的阅读话数。

**Comment by bztwh** [comment]
长按漫画信息里有纪录

**Comment by feilongfl** [comment]
> 长按漫画信息里有纪录

原来还有这功能

**Comment by bztwh** [comment]
> > 长按漫画信息里有纪录
> 
> 原来还有这功能

请问标签功能还会加回来吗
我记得好像可以自己加标签,有一个标签页面.
