### ISSUE TITLE
feature request: 希望能增加网易漫画源以及打开漫画原网页的功能

### ISSUE THREAD

**Issue by zhongfly** [feilongfl/Cimoc#6]
1，由于网易漫画上还是有一些漫画版权，比如《碧蓝之海》，所以希望能增加该漫画源。

2，如你所说，有时候想评论，有部分源(比如：漫画之家)的原网页已经有评论区了，有时候希望能看看评论区，所以希望能打开漫画的原网页(就是漫画详情那种页面)

希望开发者能酌情考虑一下这2个需求

**Comment by zhongfly** [comment]
还有就是…检查更新好像真的有点慢…(接近300漫画

**Comment by feilongfl** [comment]
1. 已添加：https://github.com/feilongfl/Cimoc/releases/tag/v1.4.8.8048
1. 打开原网页可以用分享功能直接打开
1. 检查更新这个问题我一直想处理，但是抽不出时间

**Comment by zhongfly** [comment]
最新版本没有网易源诶…是不是忘记什么了

**Comment by feilongfl** [comment]
需要清理掉数据

**Comment by feilongfl** [comment]
请先备份漫画然后清掉数据然后恢复
