### ISSUE TITLE
能多加一些源不

### ISSUE THREAD

**Issue by wujunyou33** [feilongfl/Cimoc#65]
比如《古风漫画》《360漫画》《漫画控》如果可以回头我把整理好的地址打包过来，还有大佬有qq群不！

**Comment by feilongfl** [comment]
没，不用QQ :sunglasses:

**Comment by feilongfl** [comment]
@wujunyou33 兄弟，你这一个问题的issue开的太多了😓你直接回复在下面我也能看到的

**Comment by feilongfl** [comment]
这个量可以的😓容我慢慢咕

**Comment by feilongfl** [comment]
todo list:

我要去漫画
[ ] http://m.517manhua.com/

漫画love
[ ] http://m.manhualove.com

漫画DB
[ ] https://www.manhuadb.com/

要看漫画网
[ ] http://m.yaokanmanhua.com/rexue/18477/

118漫画
[ ] http://m.lxt188.com/

666漫画
[ ] http://m.jls666.com/

秀动漫
[ ] http://www.xiudm.com/comic

皮皮漫画
[ ] https://m.pipimov.com/

399漫画
[ ] http://m.wxt999.net/comic/list/16/

好漫画
[ ] http://m.haomh.com/

滴滴嘟嘟漫画
[ ] http://m.dididudu.com/

受漫画
[ ] http://m.33am.cn/

乐乐漫画
[ ] http://m.llmanhua.com/

重庆漫画网
[ ] http://m.flcomic.com/

土蛋漫画
[ ] http://m.manhua.tudan.cc/

飞飞漫画
[ ] http://m.ffmanhua.com/

漫友八八
[ ] http://m.many88.com/manhua/11/

97漫画台
[ ] https://m.97manhua.com/

96漫画
[ ] http://m.96mh.com/

365漫画
[ ] http://m.iqg365.com/

733漫画网
[ ] http://m.733mh.com/

67漫画
[ ] http://mip.67manhua.com/

优优漫画
[ ] http://m.sfv5.com/

埃罗漫画
[ ] http://m.hlzzz.com/

韩国生肉1
[ ] https://toonkor.blue/

韩国生肉2
[ ] https://www.battlecomics.co.kr/webtoons/944

漫画铺
[ ] https://m.manhuapu.com/rexue/malaqianjindoueshao/129196.html

鬼萝莉漫画
[ ] http://m.gllmh.com/

漫画库
[ ] http://m.manhuaku.cc/

漫画牛1
[ ] https://m.manhuaniu.com/

漫画牛2
[ ] http://m.manhua666.com/

漫画台
[ ] https://m.manhuatai.com/

sf漫画
[ ] https://mm.sfacg.com/

星辰漫画
[ ] http://m.xcmh.cc/

### 需要付费

无限漫画
客户端

漫画岛
[ ] https://m.manhuadao.cn/index.html?cpid=0

叭哒
[ ] http://acn.m.iqiyi.com/comic/home

咪咕漫画
[ ] http://m.migudm.cn/

土豪漫画
[ ] https://m.tohomh.com/label/l.html

漫画柜
[ ] https://tw.manhuagui.com/（电脑版）
[ ] https://m.manhuagui.com/

汤圆漫画
[ ] http://manhua.itangyuan.com/

扑飞漫画
[ ] http://m.pufei.net/

CC图库漫画
[ ] http://m.tuku.cc/

c3yy漫画网
[ ] http://m.c3yy.com/wanjie/

古风漫画
[ ] http://m.gufengmh.com/

滴滴漫画网
[ ] http://m.nfydd.com/

吹雪漫画
[ ] http://m.chuixue.net/

漫画160
[ ] https://m.mh160.com/

来漫画
[ ] https://m.laimanhua.com/

漫画楼
[ ] https://m.baidu.com/mip/c/s/m.manhualou.com/

漫画淘
[ ] https://m.manhuatao.com/

非常爱漫
[ ] http://m.veryim.com/

72漫画
[ ] http://m.72qier.com/

哦漫画
[ ] http://m.omanhua.net/

塔多漫画
[ ] http://m.taduo.net/

亲亲漫画
[ ] http://www.duzhez.com/

漫画123
[ ] https://m.manhua123.net/

漫画1234
[ ] https://www.mh1234.com/wap/

57漫画
[ ] http://m.57mh.com/

733动漫网
[ ] https://m.733.so/

卡推漫画
[ ] http://m.700mh.com/

国漫吧
[ ] http://m.guoman8.net/

ONe漫画
[ ] https://m.onemanhua.com/

友绘漫画
[ ] http://m.wuyouhui.net/

大古漫画
[ ] https://m.dagumanhua.com/

517漫画
[ ] http://www.517mh.net/wap/

36漫画
[ ] https://m.baidu.com/paw/c/s/m.36mh.com/update/1/

超速漫画
[ ] http://m.super-d.com/

x18漫画
[ ] https://m.x18.cn/manhua/593/

522漫画
[ ] http://m.love127.com/

360漫画
[ ] http://m.xatxwh.com/

kuku动漫
[ ] http://m.kukudm.com/

﻿動漫狂
[ ] https://www.cartoonmad.com/

777漫画
[ ] http://m.777mh.com/777manhuadanmei/

动漫之家
[ ] https://manhua.dmzj.com/update_1.shtml

动漫之家
[ ] https://m.dmzj.com/

百年漫画
[ ] https://m.bnmanhua.com/

一漫网
[ ] http://m.emw162.com/

腐漫画
[ ] http://m.fummhua.com/

乙女漫画
[ ] http://m.nokiacn.net/

知音漫客
[ ] https://www.zymk.cn/

漫客栈
[ ] https://m.mkzhan.com/

动漫屋
[ ] http://m.dm5.com/manhua-new/

部分漫画付费区域

酷漫网
[ ] http://m.kuman.com/

掌阅漫画
[ ] http://m.cm233.com/

腾讯漫画
[ ] https://m.ac.qq.com/

微博动漫
[ ] http://manhua.weibo.cn/comic/home/gender

漫漫漫画
[ ] https://m.manmanapp.com/

快看漫画
[ ] http://m.kuaikanmanhua.com/

网易漫画
[ ] https://h5.manhua.163.com/

**Comment by feilongfl** [comment]
2019.3.4漫画大全（整理版）

我要去漫画
- [ ] http://m.517manhua.com/

漫画love
- [ ] http://m.manhualove.com

漫画DB
- [x] https://www.manhuadb.com/

要看漫画网
- [ ] http://m.yaokanmanhua.com/rexue/18477/

118漫画
- [ ] http://m.lxt188.com/

666漫画
- [ ] http://m.jls666.com/

秀动漫
- [ ] http://www.xiudm.com/comic

皮皮漫画
- [ ] https://m.pipimov.com/

399漫画
- [ ] http://m.wxt999.net/comic/list/16/

好漫画
- [ ] http://m.haomh.com/

滴滴嘟嘟漫画
- [ ] http://m.dididudu.com/

受漫画
- [ ] http://m.33am.cn/

乐乐漫画
- [ ] http://m.llmanhua.com/

重庆漫画网
- [ ] http://m.flcomic.com/

土蛋漫画
- [ ] http://m.manhua.tudan.cc/

飞飞漫画
- [ ] http://m.ffmanhua.com/

漫友八八
- [ ] http://m.many88.com/manhua/11/

97漫画台
- [ ] https://m.97manhua.com/

96漫画
- [ ] http://m.96mh.com/

365漫画
- [ ] http://m.iqg365.com/

733漫画网
- [ ] http://m.733mh.com/

67漫画
- [ ] http://mip.67manhua.com/

优优漫画
- [ ] http://m.sfv5.com/

埃罗漫画
- [ ] http://m.hlzzz.com/

韩国生肉1
- [ ] https://toonkor.blue/

韩国生肉2
- [ ] https://www.battlecomics.co.kr/webtoons/944

漫画铺
- [ ] https://m.manhuapu.com/rexue/malaqianjindoueshao/129196.html

鬼萝莉漫画
- [ ] http://m.gllmh.com/

漫画库
- [ ] http://m.manhuaku.cc/

漫画牛1
- [ ] https://m.manhuaniu.com/

漫画牛2
- [ ] http://m.manhua666.com/

漫画台
- [ ] https://m.manhuatai.com/

sf漫画
- [ ] https://mm.sfacg.com/

星辰漫画
- [ ] http://m.xcmh.cc/

需要付费

无限漫画
客户端

漫画岛
- [ ] https://m.manhuadao.cn/index.html?cpid=0

叭哒
- [ ] http://acn.m.iqiyi.com/comic/home

咪咕漫画
- [x] http://m.migudm.cn/

土豪漫画
- [x] https://m.tohomh.com/label/l.html

漫画柜
- [x] https://tw.manhuagui.com/（电脑版）
- [x] https://m.manhuagui.com/

汤圆漫画
- [ ] http://manhua.itangyuan.com/

扑飞漫画
- [x] http://m.pufei.net/

CC图库漫画
- [x] http://m.tuku.cc/

c3yy漫画网
- [ ] http://m.c3yy.com/wanjie/

古风漫画
- [ ] http://m.gufengmh.com/

滴滴漫画网
- [ ] http://m.nfydd.com/

吹雪漫画
- [ ] http://m.chuixue.net/

漫画160
- [ ] https://m.mh160.com/

来漫画
- [ ] https://m.laimanhua.com/

漫画楼
- [ ] https://m.baidu.com/mip/c/s/m.manhualou.com/

漫画淘
- [ ] https://m.manhuatao.com/

非常爱漫
- [ ] http://m.veryim.com/

72漫画
- [ ] http://m.72qier.com/

哦漫画
- [ ] http://m.omanhua.net/

塔多漫画
- [ ] http://m.taduo.net/

亲亲漫画
- [ ] http://www.duzhez.com/

漫画123
- [ ] https://m.manhua123.net/

漫画1234
- [ ] https://www.mh1234.com/wap/

57漫画
- [x] http://m.57mh.com/

733动漫网
- [ ] https://m.733.so/

卡推漫画
- [ ] http://m.700mh.com/

国漫吧
- [ ] http://m.guoman8.net/

ONe漫画
- [ ] https://m.onemanhua.com/

友绘漫画
- [ ] http://m.wuyouhui.net/

大古漫画
- [ ] https://m.dagumanhua.com/

517漫画
- [ ] http://www.517mh.net/wap/

36漫画
- [ ] https://m.baidu.com/paw/c/s/m.36mh.com/update/1/

超速漫画
- [ ] http://m.super-d.com/

x18漫画
- [ ] https://m.x18.cn/manhua/593/

522漫画
- [ ] http://m.love127.com/

360漫画
- [ ] http://m.xatxwh.com/

kuku动漫
- [ ] http://m.kukudm.com/

﻿動漫狂
- [x] https://www.cartoonmad.com/

777漫画
- [ ] http://m.777mh.com/777manhuadanmei/

动漫之家
- [x] https://manhua.dmzj.com/update_1.shtml

动漫之家
- [x] https://m.dmzj.com/

百年漫画
- [x] https://m.bnmanhua.com/

一漫网
- [ ] http://m.emw162.com/

腐漫画
- [ ] http://m.fummhua.com/

乙女漫画
- [ ] http://m.nokiacn.net/

知音漫客
- [ ] https://www.zymk.cn/

漫客栈
- [ ] https://m.mkzhan.com/

动漫屋
- [x] http://m.dm5.com/manhua-new/

部分漫画付费区域

酷漫网
- [ ] http://m.kuman.com/

掌阅漫画
- [ ] http://m.cm233.com/

腾讯漫画
- [x] https://m.ac.qq.com/

微博动漫
- [ ] http://manhua.weibo.cn/comic/home/gender

漫漫漫画
- [ ] https://m.manmanapp.com/

快看漫画
- [ ] http://m.kuaikanmanhua.com/

~~网易漫画~~(被B站收购不添加)
[~~https://h5.manhua.163.com/~~](https://h5.manhua.163.com/)

**Comment by ckn4** [comment]
大概看了一下，好多应该都用的同一个源，因为目录都是一样的。
感觉来漫画m.laimanhua.com这个源不错
试着做了一下，后边的包括获取图片应该都能做，可惜卡在一开始的搜索，搜索到的只有固定的一条漫画，貌似是cookie的原因。

**Comment by feilongfl** [comment]
迁移至 https://github.com/feilongfl/Cimoc/issues/68

**Comment by feilongfl** [comment]
> 大概看了一下，好多应该都用的同一个源，因为目录都是一样的。
> 感觉来漫画m.laimanhua.com这个源不错
> 试着做了一下，后边的包括获取图片应该都能做，可惜卡在一开始的搜索，搜索到的只有固定的一条漫画，貌似是cookie的原因。

这网站是看漫画的壳？链接里面写着看漫画。。。
貌似没什么难度吧，跟扑飞还有几个网站都是一个模板做出来的，这个壳搜索应该不需要cookies，一般也很少见搜索需要很复杂验证的，一般都是在最后加载图片的时候才会有各种乱七八糟的东西
