### ISSUE TITLE
关于下载问题，下载文件夹名字可否与漫画保持一致

### ISSUE THREAD

**Issue by buttu-03** [feilongfl/Cimoc#69]
如题，下载的漫画文件夹显示的都是一串数字，包括漫画名，卷名，话数名全部都是数字，可以使下载保持名字一致吗，毕竟话数多的，手动修改就显得麻烦了
![image](https://user-images.githubusercontent.com/48196735/53711947-ba5df800-3e7f-11e9-9edf-ed6bc16dd0bb.png)

**Comment by feilongfl** [comment]
这个位置应该是和原版一致的，名字好像是各个id来着，在最里层的文件夹里面有个文本文件说了他是什么漫画第几话之类的，可以读取那个来自动重命名
