### ISSUE TITLE
希望添加手机虚拟按钮自动隐藏。

### ISSUE THREAD

**Issue by bztwh** [feilongfl/Cimoc#7]
列表、评论图标点下跳打开浏览器跳zeit.co
那个登录有什么用，评论吗？

**Comment by feilongfl** [comment]
emmm，我手机没有虚拟按键，所以没考虑过这个问题
登陆暂时没用，我本来是想同步漫画数据来着，省的刷机导致数据丢失，但是数据库出了点问题。
评论的话之前网页活得好好的，不知道什么时候死了╮(╯▽╰)╭
