### ISSUE TITLE
收藏的心形按钮

### ISSUE THREAD

**Issue by Moreki** [feilongfl/Cimoc#70]
收藏漫画的按钮点按一次后🔘就变这样单纯的蓝色圆形按钮，返回再进入，按钮就正常了。

**Comment by Moreki** [comment]
[``](url)

**Comment by feilongfl** [comment]
没发现这个bug啊，请给出更详细说明

**Comment by History-exe** [comment]
复现率很低吧，我也遇到过。好像是操作太快导致的。

**Comment by Moreki** [comment]
![Screenshot_20190320-011624](https://user-images.githubusercontent.com/14026143/54627403-5148c800-4aae-11e9-880b-105ce176a2d6.png)

**Comment by feilongfl** [comment]
好吧，我试试怎么能把心弄没:joy:

**Comment by feilongfl** [comment]
没能复现
