### ISSUE TITLE
可否考虑加入搜索本地已收藏漫画功能

### ISSUE THREAD

**Issue by sunbeams001** [feilongfl/Cimoc#72]
个人收藏漫画比较多，想从已收藏里找一部特定名字的漫画似乎不太可能，尤其在dmzj源不稳定的现在，很多之前收藏的通过搜索就找不到了

或者有其他使用方法能做到搜索已收藏漫画吗

**Comment by feilongfl** [comment]
ref https://github.com/feilongfl/Cimoc/issues/128
