### ISSUE TITLE
漫画简介区域高度有限导致简介显示不全问题

### ISSUE THREAD

**Issue by ClearSights** [feilongfl/Cimoc#73]
目前文字简介区域的高度固定，似乎也无法折叠/展开，如果某个漫画的简介比较长，就会有结尾一些文字显示不全的问题。比如机动警察的动漫之家源、看漫画源就都出现了这个问题。能否在那个文字区域加一个折叠/展开功能，或是让它可滚动呢？

**Comment by feilongfl** [comment]
已增加，长按后显示在对话框中
