### ISSUE TITLE
是否可以在看漫画的时候显示通知栏

### ISSUE THREAD

**Issue by song-zi** [feilongfl/Cimoc#76]

**Comment by History-exe** [comment]
常驻显示通知栏的话感觉不太美观。
如果是可选的话还行

**Comment by feilongfl** [comment]
这个会烧屏吧...我回头看下可选吧

**Comment by song-zi** [comment]
烧屏确实是个问题。
之前是因为我的手机是水滴屏，额头有一大块黑色感觉有点别扭，所以想显示通知栏会不会好一点。
最近系统更新解决这个问题了。

**Comment by feilongfl** [comment]
最近买了个boox，发现这个貌似也是有必要加的，毕竟不都是OLED，eink显示通知栏还是很有必要的:smile: 
毕竟刷新率捉急，滑动显示通知这种东西根本没有:smile:

**Comment by feilongfl** [comment]
已添加
