### ISSUE TITLE
手动旋转功能有问题

### ISSUE THREAD

**Issue by QZBT** [feilongfl/Cimoc#79]
无法手动从竖屏转到横屏，并且只要试图手动从竖屏状态手动切换到横屏，APP会卡在竖屏状态。默认用跟随系统方向或者横屏，可以进入横屏状态。横屏状态也可以手动切到竖屏状态。但是只要试图从竖屏状态手动切换到横屏状态，APP就会卡在竖屏状态；就算是选择默认跟随系统方向，只要进行了手动方向切换操作，也会卡在竖屏状态，旋转手机亦再无反应。

**Comment by feilongfl** [comment]
横横竖竖横竖看着好晕:joy_cat:
手动切换到横屏是指从设置菜单里面么？

**Comment by sunbeams001** [comment]
已复现，不过我这里没有卡住，只是无法切换屏幕方向
手动切换指的是 自定义点击事件 里的 切换屏幕方向 吧，这个功能似乎对于竖切横事件无法正确响应

**Comment by feilongfl** [comment]
> 已复现，不过我这里没有卡住，只是无法切换屏幕方向
> 手动切换指的是 自定义点击事件 里的 切换屏幕方向 吧，这个功能似乎对于竖切横事件无法正确响应

哦，这个功能忘测试了哈😂

**Comment by QZBT** [comment]
https://github.com/feilongfl/Cimoc/issues/79#issuecomment-472391984
对的.点击和长按自定义都无效.我这边不管什么情况下.只要用了这个功能.就会卡在竖屏状态.

**Comment by QZBT** [comment]
https://github.com/feilongfl/Cimoc/issues/79#issuecomment-472422807
哈哈有时间修复一下就好了.偶尔看没有分割的大图会用到手动横屏.现在暂时用跟随系统方向.

**Comment by feilongfl** [comment]
已修正
