### ISSUE TITLE
网易漫画的源好像不行了

### ISSUE THREAD

**Issue by mixjam** [feilongfl/Cimoc#8]

**Comment by feilongfl** [comment]
@waxleid 
看漫画没记错是要翻墙的

请左转shadowsocks或v2ray或xx-net

**Comment by saasddsaasdd** [comment]
大佬，看漫画的源可以通过https://tw.manhuagui.com直接访问，无需翻墙，跪求大佬添加。这是我最喜欢的一个源，看着它从seemh到ikanman到现在的manhuagui，他的图库和图源都是最棒的。

**Comment by mixjam** [comment]
@feilongfl 改了问题

**Comment by feilongfl** [comment]
@waxleid 
这种情况应该重新开一个issue...

**Comment by feilongfl** [comment]
移动到
https://github.com/feilongfl/Cimoc/issues/11
