### ISSUE TITLE
软件功能疑问

### ISSUE THREAD

**Issue by History-exe** [feilongfl/Cimoc#83]
在app的图源里进入某个图源。
如动漫之家V2图源，可以在这个图源内查看下属的所有漫画，还可以分类型搜索。
但是在一些新添加图源进行相同的操作没有反应，提示信息是操作失败，请问是没做相关的功能，还是出现了问题。

**Comment by zhongfly** [comment]
没做这个功能吧

**Comment by feilongfl** [comment]
恩，我确实偷懒没做分类 😄

**Comment by History-exe** [comment]
@feilongfl 这样啊，那没问题了😂
