### ISSUE TITLE
百年漫画无法解析

### ISSUE THREAD

**Issue by Steve-337** [feilongfl/Cimoc#84]
# 这是一个漫画源问题

> 请您在提交本问题前仔细完成下面问题以便更好地解决问题.
> 如果有多个漫画源出错，请不要合并在一起，谢谢

## 出现错误的漫画源
百年漫画
## 您搜索/观看的漫画名称或关键字以及访问链接
疑似后宫
## 在以下环节中出现错误
- [ ✔] 搜索
- [✔ ] 章节信息
- [ ✔] 图片加载

## 你是否使用科学上网工具
- [ ] 是
- [✔ ] 否

## 你是否能够访问漫画源网页并成功加载漫画图片
- [ ✔] 是
- [ ] 否

## 您手机的系统版本
- [ ] 原生(AOSP/LL/RR/Mokee等)
- [ ] 国产(小米/氢氧/锤子)
具体版本: 
三星安卓4.1.2
## 您使用的cimoc版本
V1.4.15(334)

**Comment by feilongfl** [comment]
这个我这边是正常的，你要不再试下？

**Comment by Steve-337** [comment]
ok,我先更新一下

**Comment by Steve-337** [comment]
仍然解析失败啊……

**Comment by Steve-337** [comment]
我好像知道问题所在了，好像是系统浏览器内核问题（我是用chrome浏览器来看源网页的，我试了下系统浏览器，发现系统浏览器好像加载不出来图片）

**Comment by feilongfl** [comment]
我手里面没有安卓4的机器了，之前的华为3x被我充电把电池弄挂了，顺便emmc也跪了，死的很彻底

至于是不是浏览器内核的问题我就不知道了，我感觉程序没用浏览器内核吧

**Comment by Steve-337** [comment]
那我再试试吧，挺好的漫画源我却用不了……

**Comment by LenKiMo** [comment]
百年漫画问题还挺多的。一边是漫画源网页内图片就已经丢失，一边是许多漫画章节列表每一话都会显示两遍，能不能看还有点靠运气……

**Comment by feilongfl** [comment]
@LenKiMo 这个漫画源来自pr，我只测试了几个漫画:cry: 
我抽时间再看下吧
