### ISSUE TITLE
搜索结果重复展示

### ISSUE THREAD

**Issue by LenKiMo** [feilongfl/Cimoc#85]
V1.4.15

以关键词『魔物娘』，勾选『严格搜索』选项进行搜索，不断下拉搜索结果进行获取时，会注意到 2animx 的『魔物娘』『魔物娘的（相伴）日常』两部作品的搜索结果反复出现。

该现象在连续搜索几次后均可重复复现，目前没有观察到其它关键词出现类似情况。

**Comment by zhongfly** [comment]
搜索 LV999的村民 也会出现(注意大写)

**Comment by feilongfl** [comment]
fixed
