### ISSUE TITLE
『严格搜索』匹配问题

### ISSUE THREAD

**Issue by LenKiMo** [feilongfl/Cimoc#86]
V1.4.19

目前，严格搜索选项应该是指搜索关键字在作品名中任意一处完全匹配而不被割裂。

但是其中也包含了英文的严格大小写匹配，这就使得在中文环境下搜索中英混输的作品名时存在困难。

例如，以『最终boss』为关键词进行严格搜索，能够击中『我在最终boss的魔王城前开教会』，但无法搜索到『野生的最终BOSS出现了』，因为后者的『Boss』一词是全大写的。

难解的是，漫画网站在录入包含中英双语的作品名称时，英文如何书写全无定数，可能是『boss』，也可能是『BOSS』，还可能是『Boss』。这就使得目前的严格搜索在有时候可能会过于严苛，但倘若不勾选此项，搜索结果又会更加杂乱而难以找到目标。

理想的解决方式应该是在严格搜索中忽略英文字母的大小写问题，但不知道这方面优化是否存在困难，或是与原有设计目的不符，姑且写下作为 issue 提交以供开发者参考。

**Comment by feilongfl** [comment]
严格搜索指作品名或作者名
我下午看看

**Comment by feilongfl** [comment]
已添加，随下一版本一起更新
