### ISSUE TITLE
长按作品名或作者名操作相关

### ISSUE THREAD

**Issue by LenKiMo** [feilongfl/Cimoc#87]
V1.4.19

目前，在漫画详情页中长按作品名、作者名或作品详情时，会有一次短振动，但不会引发其它任何行为。这应该是继承自原版的特征。

不过，包含振动却不会有其它结果可能会使用户产生疑惑，建议考虑将其实现为长按复制相关文字到剪贴板，或是去掉这一振动效果。

**Comment by feilongfl** [comment]
已复现

**Comment by feilongfl** [comment]
fixed
