### ISSUE TITLE
阅读模式下右上角时间显示问题

### ISSUE THREAD

**Issue by Steve-337** [feilongfl/Cimoc#89]
在阅读模式下，右上角的时间小时只显示HH，分钟显示正常，不知道是不是系统版本低的问题。现在我都是下载APK后自己将classes.dex里面的HH:mm修改为h:mm（如果是系统问题的话那就不用管这个issue了，我自己修改自己用）

**Comment by feilongfl** [comment]
@Steve-cn 系统环境是？

**Comment by Steve-337** [comment]
@feilongfl 安卓4.1.2

**Comment by feilongfl** [comment]
@Steve-cn 哦，那个三星的，我没注意是一个人的issue
这个我试试能不能复现吧

**Comment by feilongfl** [comment]
搜索了一下
https://stackoverflow.com/questions/17341214/difference-between-java-hhmm-and-hhmm-on-simpledateformat
kk: (01-24) will look like 01, 02..24.
HH:(00-23) will look like 00, 01..23.
hh:(01-12 in AM/PM) will look like 01, 02..12.
这个应该是没有问题的，换成h就是十二小时制了

**Comment by Steve-337** [comment]
但是为何我的只显示HH呢？与我手机是12小时模式有关？（有时间我试试其他同安卓版本不同型号的手机）（好吧，与12小时模式无关）
