### ISSUE TITLE
Bug?:当一话只有1页时不会自动加载下一话

### ISSUE THREAD

**Issue by zhihaofans** [feilongfl/Cimoc#9]
当打开一话只有1页的漫画时不会自动加载下一话，得手动点下一话

**Comment by feilongfl** [comment]
emmm.没看过一页的漫画😥
什么漫画是一页的,给个连接看下

@zhihaofans

**Comment by zhihaofans** [comment]
`动漫之家v2` 源的 [`总之就是非常可爱`](https://m.dmzj.com/info/zongzhijiushifeichangkeaiflymetothemoon.html) 的 `作者婚约发表` 章节，自动加载下一话得在滑动最后一P时才生效，自动切割大图打开后被切割的大图也可以自动加载下一话。

对了，`布卡漫画` 源的 [`我的百合乃工作是也！`](http://www.buka.cn/detail/219462.html) 和 `CC图库` 源的 `我们无法一起学习` 都解析失败 

@feilongfl
