### ISSUE TITLE
搜索界面『图源选择』选项无法保存

### ISSUE THREAD

**Issue by LenKiMo** [feilongfl/Cimoc#90]
应用版本：
V1.4.21

设备与系统：
Meizu Pro 6 Plus
Flyme 7.2.0.0A with Android 7.0.0

问题描述：
搜索界面中的图源选择选项，在应用退出后会被重置为全部勾选的初始状态，无法保存选择。

重现步骤：
1. 在搜索界面，点击按钮打开图源选择列表，取消一部分选项，按确定保存。
2. 保存后再次打开列表，可观察到取消勾选的状态仍然保持。
3. 发起一次搜索，确认取消勾选的漫画源不在结果中出现。
4. 返回搜索界面打开列表，可观察到取消勾选的状态仍然保持。
5. 通过 Back 键正常退出应用。
6. 应用再启动后，打开搜索界面，调出图源选择列表，观察到返回至所有图源都被勾选的初始状态。取消勾选的部分在退出后被重置。

**Comment by ckn4** [comment]
这个逻辑就是这么设计的吧，在搜索界面只是临时取消某些图源的搜索，如果想下一次也不启用某些图源的话，直接在图源里取消。我觉得这种操作逻辑没啥问题。

**Comment by LenKiMo** [comment]
啊……好像确实是这样……都忘了还有个独立的图源菜单了……
