### ISSUE TITLE
无法检查更新

### ISSUE THREAD

**Issue by LenKiMo** [feilongfl/Cimoc#92]
V1.4.21
Meizu Pro 6 Plus
Android 7.0.0

在前几日动漫之家源维护结束过后，动漫之家、动漫之家 V2 两个源恢复到可以正常浏览的状态。但是以这两个源为主的漫画库开始无法检查到任何漫画的的更新信息。

因为有几百部收藏在，所以应该不至于当真一部作品更新都没有。但是无法判断是不是个案，所以借 issue 来询问有没有什么排查方法……

在启用和关闭代理的情况下都进行过更新检查，均为无更新结果。

**Comment by feilongfl** [comment]
动漫之家那边我看还是维护中呢？
我这边动漫之家v2貌似没问题，请给出几部漫画

**Comment by ckn4** [comment]
是动漫之家就根本没更新，官方说法是维护这几天的更新会慢慢补上。

**Comment by Steve-337** [comment]
@feilongfl 我倒是遇到了手动看有更新但是检查更新时不提示的问题，现在我都是把自己最想看的漫画一个个手动点击看有没有更新（不提示的好像都是在列表靠下面的漫画）

**Comment by LenKiMo** [comment]
今晨已确认到动漫之家源恢复更新提示。关闭 Issue。
