### ISSUE TITLE
下载问题

### ISSUE THREAD

**Issue by TheCardistry** [feilongfl/Cimoc#93]
# 这是一个漫画源问题

> 请您在提交本问题前仔细完成下面问题以便更好地解决问题.
> 如果有多个漫画源出错，请不要合并在一起，谢谢

## 出现错误的漫画源
扑飞漫画
## 您搜索/观看的漫画名称或关键字以及访问链接
所有漫画
## 在以下环节中出现错误
 可以正常加载图片，但无法下载
## 你是否使用科学上网工具
否

## 你是否能够访问漫画源网页并成功加载漫画图片
 是

## 您手机的系统版本
国产(小米 红米Pro)
具体版本: MIUI10 9.3.21

## 您使用的cimoc版本
V1.4.21

**Comment by feilongfl** [comment]
无法复现:sob:
