### ISSUE TITLE
[CS]

### ISSUE THREAD

**Issue by GalaxyAlpha** [feilongfl/Cimoc#96]
# 这是一个漫画源问题

> 请您在提交本问题前仔细完成下面问题以便更好地解决问题.
> 如果有多个漫画源出错，请不要合并在一起，谢谢

## 出现错误的漫画源
手机汗汗/汗汗漫画

## 您搜索/观看的漫画名称或关键字以及访问链接
所有漫画

## 在以下环节中出现错误
- [✔] 搜索
- [✔] 章节信息
- [✔] 图片加载

## 你是否使用科学上网工具
- [✔] 否

## 你是否能够访问漫画源网页并成功加载漫画图片
- [✔] 是

## 您手机的系统版本
- [✔] 国产(小米/氢氧/锤子)
具体版本: EMUI:4.0.3，Android6.0

## 您使用的cimoc版本
V1.4.21(358)

## 建议
两个图源都源自[http://www.hhimm.com/](url)，保留一个就可以了，希望能得到修复。
另外如方便的话可否提供捐赠方式。

**Comment by feilongfl** [comment]
我这是随心情更新，本来主要部分都是别人做的，捐赠就算了吧
