### ISSUE TITLE
咪咕源有点问题

### ISSUE THREAD

**Issue by ParanoiaIsGreat** [feilongfl/Cimoc#97]
没找到其他漫画，我看的是《极刑饭》
页码有问题，实际页码＝显示页码+1
而且强行拖进度条到最后一页，因为“最后一页”不存在，所以会闪退

**Comment by ParanoiaIsGreat** [comment]
不影响观看，只是个小问题

**Comment by feilongfl** [comment]
@jcyxxx 漫画源？
